### ISSUE TITLE
brand-v3.0.2 publish list

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#175]
#### Tasks
- [ ] https://github.com/blockstack/designs/issues/174: blockstack design system
- [ ] https://github.com/blockstack/designs/issues/7: Design new blockstack architecture diagram
- [ ] https://github.com/blockstack/designs/issues/129: brand update to api.blockstack.com
