### ISSUE TITLE
21 task release

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#200]
@pstan26 as discussed, since we are doing outbound we need to have a consistent brand when potential devs land on each item in 21 task release onboarding process.

The following is a new 21 task release so that you can see what the process will be for Saturday morning.
```
Deadline: Mon, Feb 20, 2017
```

#### Tasks
- [x] https://github.com/blockstack/blockstack.org/issues/229: add landing view background image for mobile, tablet & desktop
- [x] https://github.com/blockstack/designs/issues/68: blockstack gradient color production
- [x] https://github.com/blockstack/blockstack-browser/issues/224: iterate the design of the portal dashboard
- [x] https://github.com/blockstack/blockstack-browser/issues/225: ui build of the latest iteration of the portal dashboard design
- [x] https://github.com/blockstack/blockstack-portal/issues/235: design hello blockstack app to be consistent with brand
- [x] https://github.com/blockstack/blockstack-portal/issues/236: hello blockstack ui build
- [x] https://github.com/blockstack/designs/issues/197: Create 480x480 Blockstack logo for 21co
- [ ] https://github.com/blockstack/designs/issues/198: Create banner image for 21co
- [ ] https://github.com/blockstack/designs/issues/187: Create "Hello World" title slide for video tutorial

**Comment by guylepage3** [comment]
@pstan26 i realized that i need to add finalize the portal dashboard before this release can be complete. I won't make tomorrow's timeline for this. can we push this for end of day monday?

**Comment by pstan26** [comment]
@guylepage3 That's totally fine. In speaking with Ryan, the closer this thing launches to the time that all of our developer tools etc work well together, the better. I'm speaking to the 21 guys today about a launch date in the future (even a week or two after monday). Thanks

**Comment by guylepage3** [comment]
@pstan26 what is the new deadline for this? I thought i saw somewhere that the goal posts have moved.

**Comment by pstan26** [comment]
@guylepage3 Just need the banner image by before Mar 15. We are releasing the Hello Blockstack Tutorial on Mar 17th, and the 21task will be launched on Mar 20th

**Comment by guylepage3** [comment]
@pstan26 can we close this issue?

**Comment by pstan26** [comment]
yep

>close #200
