### ISSUE TITLE
print production for blockstack stickers

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#257]
Create printer ready files for blockstack stickers

**Tasks** - solo bug sticker
- [x] outline all fonts and strokes
- [x] clip paths to ensure no overlapping
- [x] tidy up vector edges
- [x] reduce number of vector nodes
- [x] convert RGB to CMYK
  >Looks like there's no way for us to tell what color we'll be getting on the Blockstack brand when converting from our chosen RGB colors to print's CMYK color system.
- [x] check to make sure colors are correct
- [x] confirm registration crop marks
- [x] confirm sizing
- [x] create printer notes
- [x] run print ready files through pre-flight
- [x] verify pre-flight adjustments
- [x] export and compress files for printer

**Tasks** - horizontal sticker
- [x] outline all fonts and strokes
- [x] clip paths to ensure no overlapping
- [x] tidy up vector edges
- [x] reduce number of vector nodes
- [x] convert RGB to CMYK
- [x] check to make sure colors are correct
- [x] create printer notes
- [x] confirm registration crop marks
- [x] confirm sizing
- [x] run print ready files through pre-flight
- [x] verify pre-flight adjustments
- [x] export and compress files for printer

**Tasks** - vertical sticker
- [x] outline all fonts and strokes
- [x] clip paths to ensure no overlapping
- [x] tidy up vector edges
- [x] reduce number of vector nodes
- [x] convert RGB to CMYK
- [x] check to make sure colors are correct
- [x] create printer notes
- [x] confirm registration crop marks
- [x] confirm sizing
- [x] run print ready files through pre-flight
- [x] verify pre-flight adjustments
- [x] export and compress files for printer

**Printer specs**
https://www.stickermule.com/products/die-cut-stickers
Die cut template — https://www.stickermule.com/template/die-cut-stickers

**Comment by guylepage3** [comment]
![blockstack-sticker-bug-solo-2x2](https://cloud.githubusercontent.com/assets/1711854/25820365/02f92996-33ff-11e7-9dc8-2a5b2eb8c834.png)

[blockstack-sticker-bug-solo-2x2.ai.zip](https://github.com/blockstack/designs/files/984564/blockstack-sticker-bug-solo-2x2.ai.zip)

**Comment by guylepage3** [comment]
<img width="522" alt="blockstack-sticker-horizontal 2x" src="https://cloud.githubusercontent.com/assets/1711854/25821578/b3260858-3403-11e7-8ba1-6a3b0e9c26e9.png">

[blockstack-sticker-horizontal.ai.zip](https://github.com/blockstack/designs/files/984638/blockstack-sticker-horizontal.ai.zip)

@pstan26 we will need to order these in a custom 4.5" x 1.25" format and the folks at stickermule.com will use the die line to cut the stickers.

**Comment by pstan26** [comment]
K this means we are ready to order i assume...thumbs up and I'll put it in

**Comment by guylepage3** [comment]
<img width="414" alt="blockstack-sticker-vertical 2x" src="https://cloud.githubusercontent.com/assets/1711854/25822250/f8503320-3405-11e7-809b-f26672a11746.png">

[blockstack-sticker-vertical.ai.zip](https://github.com/blockstack/designs/files/984678/blockstack-sticker-vertical.ai.zip)

@pstan26 we will need to order these in a custom 3" x 3" format and the folks at stickermule.com will use the die line to cut the stickers.

**Comment by guylepage3** [comment]
Yes. all 3 are now ready to order. 😄

**Comment by pstan26** [comment]
Sticker order in. :-)
