### ISSUE TITLE
design standup - Wed, Jul 19, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#347]
**Yesterday** Nothing.

**Today** I plan to familiarize with blockstack.org `main.css` file and start breaking everything up into our 37 categories in order to prepare our design system.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- Continued working on reviewing pull request for @estermer
- Finalized researching `git flow`
- [x] Finalized designs for on-boarding screens
- [x] Redesigned status bar to look more like a browser
- [x] Built new status bar file for sharing with design team
- [x] Reviewed 

_**today**_:
- [ ] https://github.com/blockstack/blockstack.org/issues/323: update hero design
- [ ] Merge @yknl's PR https://github.com/blockstack/blockstack-browser/pull/630: Design update to profile view into browser
- [ ] Merge @estermer's PR https://github.com/blockstack/blockstack-browser/pull/626: Fixed Flexbox for Safari into browser
- [ ] Finalize review pull request process for @estermer
- [ ] Review @arisgk pull request on blockstack.org
- [ ] https://github.com/blockstack/blockstack-browser/issues/634: Update the Status Bar items and design to new design
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/632: Auto-generate large profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] UI build of project Apollo website design
- [ ] Build UI for on-boarding screens (if @larrysalibra is complete on his end)

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/347
