### ISSUE TITLE
design standup - Thu, Jul 20, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#348]
**Yesterday** Started restructuring blockstack.org `main.css` file.

**Today** I will not be able to contribute.

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Nothing

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] https://github.com/blockstack/blockstack-browser/issues/637: build ui of on-boarding screens
    - included updates to all modals and forms in the browser

_**today**_:
- [ ] https://github.com/blockstack/designs/issues/349: Tutorial Intro Slide for Video and Blog post
- [ ] Design project apollo site
- [ ] https://github.com/blockstack/blockstack-browser/issues/634: Update the Status Bar items and design to new design
- [ ] https://github.com/blockstack/blockstack-browser/issues/632: Auto-generate large profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] https://github.com/blockstack/blockstack.org/issues/323: update hero design
- [ ] https://github.com/blockstack/designs/issues/350: Video Bumper
- [ ] Merge @estermer's PR https://github.com/blockstack/blockstack-browser/pull/626: Fixed Flexbox for Safari into browser
- [ ] Finalize review pull request process for @estermer
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Review @arisgk pull request on blockstack.org
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/347
