### ISSUE TITLE
design standup – Tue, Aug 1, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#375]
_**tuesday —› thursday**_:
- Focus was on project Blockstack Token site and browser and all tasks for Summit. Full heads down
- [x] https://github.com/blockstack/blockstack-browser/issues/634: Update the Status Bar items and design to new design
- [x] https://github.com/blockstack/blockstack-browser/issues/632: Auto-generate large profile

_**friday —› sunday**_:
- Time off for entire Blockstack team

_**yesterday**_: 
- [x] https://github.com/blockstack/blockstack.org/issues/371: basic org of blockstack summit design files for community
- [x] https://github.com/blockstack/blockstack.org/issues/372: logo production on blockstack summit 2017 logo v1.0
- [x] Quick push out of powerpoint template

_**today**_:
- [x] Review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Review [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] Organize `Sprint v0.13` and move over/close out previous `Sprint v0.12`
- [x] [finalize design and ui build of new status bar design](https://github.com/blockstack/blockstack-browser/issues/662)
- [x] [update design and update beacon app icon on browser](https://github.com/blockstack/blockstack-browser/issues/663)
- [x] [resolve status bar is clickable and scrollable when modal is open](https://github.com/blockstack/blockstack-browser/issues/642)

_**ahead**_:
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- [#375: design standup - Tue, Aug 1, 2017](https://github.com/blockstack/designs/issues/375)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Open to suggestions any quick fixes that need to be tackled

@guylepage3 are you reviewing the safari flexbox PR that was already merged? or are you reviewing the contrib process? I think I am waiting on the contribution PR to be done so I can replicate it through the other repo's.

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by guylepage3** [comment]
>@guylepage3 are you reviewing the safari flexbox PR that was already merged? or are you reviewing the contrib process?

@estermer i'll be reviewing the contribution process.

**Comment by guylepage3** [comment]
Added
- [ ] re-organize `Sprint v0.13`
