### ISSUE TITLE
design standup – Wed, Aug 2, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#376]
**Yesterday** Nothing
**Today** I plan to read our new contributing guidelines and adapt my video padding PR.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Review [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] Organize `Sprint v0.13` and move over/close out previous `Sprint v0.12`
- [x] [finalize design and ui build of new status bar design](https://github.com/blockstack/blockstack-browser/issues/662)
- [x] [update design and update beacon app icon on browser](https://github.com/blockstack/blockstack-browser/issues/663)
- [x] [resolve status bar is clickable and scrollable when modal is open](https://github.com/blockstack/blockstack-browser/issues/642)

_**today**_:
- [ ] Review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [ ] Review [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [ ] [design new native macOS layout of browser](https://github.com/blockstack/blockstack-browser/issues/621)

_**ahead**_:
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- [#376: design standup - Wed, Aug 2, 2017](https://github.com/blockstack/designs/issues/376)
