### ISSUE TITLE
design standup – Thu, Aug 3, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#377]
_**yesterday**_: 
- [x] Continued review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Continued review [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] worked on [design new native macOS layout of browser](https://github.com/blockstack/blockstack-browser/issues/621)

_**today**_:
- [ ] Work on [design new native macOS layout of browser](https://github.com/blockstack/blockstack-browser/issues/621)
- [ ] Finalize review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [ ] Merge [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [live design blockstack summit 2017 summary page](https://github.com/blockstack/blockstack.org/issues/354)

_**ahead**_:
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- [#377: design standup - Thu, Aug 3, 2017](https://github.com/blockstack/designs/issues/377)

**Comment by guylepage3** [comment]
Update. Added...
- [ ] [live design blockstack summit 2017 summary page](https://github.com/blockstack/blockstack.org/issues/354)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Going to tackle the comments made on the contribution guide by the maintainers

**Comment by arisgk** [comment]
**Yesterday** Updated video padding PR to comply with @estermer new contribution guidelines
**Today** Nothing
