### ISSUE TITLE
design standup – Wed, Aug 9, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#388]
_**yesterday**_: 
Been sick for past few days and have not got much done.

_**today**_:
- [x] Finalize review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Merge [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] Organize [Sprint: 0.14](https://github.com/orgs/blockstack/projects/6)
- [x] Create [v0.14.0 release overview](https://github.com/blockstack/blockstack/issues/325)
- [x] Create prototype links and sync edit profile layouts to invision browser prototype. New browser designs that implemented new browser discovery.. [Browser v0.14 (macOS)](https://invis.io/P5CYZSIZT#/247226608_desktop)
- [x] Resolved symbols in sketch `browser-v0.14.sketch` file
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)

_**ahead**_:
- [ ] https://github.com/blockstack/blockstack.org/issues/354: live design blockstack summit 2017 summary page
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#388: design standup - Wed, Aug 9, 2017](https://github.com/blockstack/designs/issues/388)

**Comment by estermer** [comment]
**Yesterday:** Made sure there weren't any current outstanding reviews on the contrib guide.
**Today:** keeping an eye out for updates on contrib guide to make the quick changes.

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by guylepage3** [comment]
Added;
- [ ] Organize [Sprint: 0.14](https://github.com/orgs/blockstack/projects/6)
- [ ] Create [v0.14.0 release overview](https://github.com/blockstack/blockstack/issues/325)
