### ISSUE TITLE
design standup – Thu, Aug 10, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#389]
**Yesterday** Nothing
**Today** I plan to work on https://github.com/blockstack/blockstack.org/issues/363

**Comment by estermer** [comment]
**Yesterday:** Tried to clear commits from the PR on contrib guidelines to resolve PR conflicts.
**Today:** Nothing

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Finalize review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Merge [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] Organize [Sprint: 0.14](https://github.com/orgs/blockstack/projects/6)
- [x] Create [v0.14.0 release overview](https://github.com/blockstack/blockstack/issues/325)
- [x] Create prototype links and sync edit profile layouts to invision browser prototype. New browser designs that implemented new browser discovery.. [Browser v0.14 (macOS)](https://invis.io/P5CYZSIZT#/247226608_desktop)
- [x] Resolved symbols in sketch `browser-v0.14.sketch` file

_**today**_:
- [ ] Merge [#364: Create Contributing Guide](https://github.com/blockstack/blockstack.org/pull/364) for @estermer 
- [ ] https://github.com/blockstack/blockstack.org/issues/354: live design blockstack summit 2017 summary page

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#389: design standup – Thu, Aug 10, 2017](https://github.com/blockstack/designs/issues/389)

**Comment by guylepage3** [comment]
Added:
- [ ] Merge [#365: Remove constant iframe height](https://github.com/blockstack/blockstack.org/pull/365) on videos for @arisgk
