### ISSUE TITLE
design standup – Fri, Aug 11, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#391]
**Yesterday** Worked on video iframe height issue.

**Today** I plan to fix video aspect ratio.

**Comment by estermer** [comment]
**Yesterday:** submitted this [PR](https://github.com/blockstack/blockstack.org/pull/364) to finalize the contrib guidelines for blockstack.org
**Today:** going to make the updates to the blockstack designs contrib guide to match the .org so that PR can be reviewed and merged as well.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Merge [#364: Create Contributing Guide](https://github.com/blockstack/blockstack.org/pull/364) for @estermer 
- [x] Review [#365: Remove constant iframe height](https://github.com/blockstack/blockstack.org/pull/365) on videos for @arisgk
- [x] https://github.com/blockstack/blockstack.org/issues/354: live design blockstack summit 2017 summary page
- [x] Blockstack summit 2017 email banner image design

_**today**_:
- [ ] Resolve [#366: fixed images on safari mobile not scaling](https://github.com/blockstack/blockstack.org/issues/366)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)

_**ahead**_:
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#391: design standup – Fri, Aug 11, 2017](https://github.com/blockstack/designs/issues/391)
