### ISSUE TITLE
design standup – Sat, Aug 12, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#393]
_**friday**_: 
- [x] Resolve [#366: fixed images on safari mobile not scaling](https://github.com/blockstack/blockstack.org/issues/366)
- [x] Started discussion of project Kiwi w/@pstan26 

_**today**_:
- [x] Meeting with @pstan26 to discuss project Kiwi
- [x] Start design of project Kiwi website

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#393: design standup – Sat, Aug 12, 2017](https://github.com/blockstack/designs/issues/393)
