### ISSUE TITLE
design standup – Mon, Aug 14, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#394]
_**last week**_: 
- [x] Finalize review of [#330: Added Contributing Guidelines](https://github.com/blockstack/blockstack.org/pull/330) for @estermer
- [x] Merge [#347: Adjusted video padding in tutorials page](https://github.com/blockstack/blockstack.org/pull/347) @arisgk pull request on blockstack.org
- [x] Organize [Sprint: 0.14](https://github.com/orgs/blockstack/projects/6)
- [x] Create [v0.14.0 release overview](https://github.com/blockstack/blockstack/issues/325)
- [x] Create prototype links and sync edit profile layouts to invision browser prototype. New browser designs that implemented new browser discovery.. [Browser v0.14 (macOS)](https://invis.io/P5CYZSIZT#/247226608_desktop)
- [x] Resolved symbols in sketch `browser-v0.14.sketch` file
- [x] Merge [#364: Create Contributing Guide](https://github.com/blockstack/blockstack.org/pull/364) for @estermer 
- [x] Review [#365: Remove constant iframe height](https://github.com/blockstack/blockstack.org/pull/365) on videos for @arisgk
- [x] https://github.com/blockstack/blockstack.org/issues/354: live design blockstack summit 2017 summary page
- [x] Blockstack summit 2017 email banner image design
- [x] Resolve [#366: fixed images on safari mobile not scaling](https://github.com/blockstack/blockstack.org/issues/366)
- [x] Started discussion of project Kiwi w/@pstan26 
- [x] Meeting with @pstan26 to discuss project Kiwi
- [x] Start design of project Kiwi website

_**today**_:
- [x] Setup quick static site for Kiwi project
- [ ] Create react app for kiwi project website 
- [ ] Finalize hero design of project Kiwi website
- [ ] Start build of project Kiwi website

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#394: design standup – Mon, Aug 14, 2017](https://github.com/blockstack/designs/issues/394)

**Comment by estermer** [comment]
**Friday:** reviewed the changes done to the merged contrib guide to get applied to other repos
**Today:** will try to complete the contrib guide for designs.

**Comment by guylepage3** [comment]
@estermer did you create a github issue for that? we should have some back and forth on that before executing a pull request.

**Comment by estermer** [comment]
[Here is the issue](https://github.com/blockstack/designs/issues/293)

**Comment by arisgk** [comment]
**Friday** Worked on page-specific meta data.
**Today** Nothing.

**Comment by guylepage3** [comment]
@estermer moved the original issue and created a new one for the design contribution guidelines as quite a few things have changed since we started working on them.

Moved here... https://github.com/blockstack/designs/issues/395

**Comment by guylepage3** [comment]
@estermer as stated in slack.

@muneeb-ali  has brought up a nice little issue that could be right up your ally. https://github.com/blockstack/blockstack.org/issues/350. He has requested that we bump the priority level of this issue as there are community members mentioning this issue on twitter more and more frequently.

Could we get you to move over to this issue before jumping on the design contribution guidelines?

@shea256 will be working on the language as well.
