### ISSUE TITLE
design standup – Tue, Aug 15, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#396]
**Yesterday** Nothing.
**Today** I plan to work on page-specific meta data.

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** finish the `yo blockstack:react` generator

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Setup quick static site for Kiwi project

_**today**_:
- [x] [Create react app for kiwi project website](https://github.com/blockstackinc/signature-fund/issues/3)
- [ ] Finalize hero design of project Kiwi website
- [ ] Start build of project Kiwi website

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#394: design standup – Mon, Aug 14, 2017](https://github.com/blockstack/designs/issues/394)
