### ISSUE TITLE
design standup - Wed, Aug 16, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#399]
**Yesterday:** I was able to finish up the issues with my old PR on the `yo blockstack:react` generator. I also made the changes to the design contribution guide to replicate what was done on the guide for the .org repo.

**Today:** Nothing

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Finalize hero design of project Kiwi website
- [x] Build of project Kiwi website

_**today**_:
- [x] Pushed Signature Fund site live and then rested 
- [x] Resolve a couple spacing issues with funding page on blockstack.org
- [x] Start setup of new computer

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#399: design standup – Tue, Aug 15, 2017](https://github.com/blockstack/designs/issues/399)
