### ISSUE TITLE
design standup - Fri, Aug 18, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#402]
**Yesterday:** merged some of my work into a new branch for angular2 generator
**Today:** Going to read up on [Git LFS](https://git-lfs.github.com/) for the designs contribution guide.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Resolve issues with `Git LFS` so that I may download the design files onto new machine
- [x] Finalized setup of new computer
- [x] Respond to GitHub issue comments including review of new [FAQ suggestions](https://github.com/blockstack/blockstack.org/issues/374)
- [x] [Design production work and build out svg images for blockstack.org/funding partners](https://github.com/blockstack/blockstack.org/issues/375)
- [x] Merged in a couple small pull requests
- [x] Setup Sprint: 0.15
- [ ] [Worked on resolving issue with logos on funding page](https://github.com/blockstack/blockstack.org/issues/377)

_**today**_:
- [ ] [Resolve breakage with logos on funding page](https://github.com/blockstack/blockstack.org/issues/377)
- [ ] [Tighten up funding page](https://github.com/blockstack/blockstack.org/issues/376)
- [ ] [Live design name registration pages](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#402: design standup – Fri, Aug 18, 2017](https://github.com/blockstack/designs/issues/402)

**Comment by arisgk** [comment]
**Yesterday** Researched on page specific meta data solutions
**Today** Nothing
