### ISSUE TITLE
design standup – Sat, Aug 19, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#403]
_**yesterday**_: 
- [x] [Resolved breakage with logos on funding page](https://github.com/blockstack/blockstack.org/issues/377). Turned out to be a very strange SVG issue as commented in the issue.
- [x] [Worked on tightening up funding page](https://github.com/blockstack/blockstack.org/issues/376)

_**today**_:
- [x] [Worked on tightening up funding page](https://github.com/blockstack/blockstack.org/issues/376)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#403: design standup – Sat, Aug 19, 2017](https://github.com/blockstack/designs/issues/403)
