### ISSUE TITLE
design standup – Mon, Aug 21, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#405]
_**last week**_: 
- [x] Setup quick static site for Signature fund page and pushed it live on Wed
- [x] Resolved some issues with blockstack.org
- [x] Setup of new computer
- [x] [Worked on live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**today**_:
- [ ] [Finalize live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)
- [ ] [Update all button type and spacing on browser](https://github.com/blockstack/blockstack-browser/issues/693)
- [ ] [Review @estermer's README.md contribution](https://github.com/blockstack/blockstack.org/issues/378)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#405: design standup – Mon, Aug 21, 2017](https://github.com/blockstack/designs/issues/405)

**Comment by arisgk** [comment]
**Friday & Weekend** Nothing
**Today** I plan to work on blockstack.org videos aspect ratio issue.

**Comment by guylepage3** [comment]
>I plan to work on blockstack.org videos aspect ratio issue.

@arisgk take a look at my latest solution for video on the funding page’s latest commit from the `develop` branch https://github.com/blockstack/blockstack.org/network.

Seeing this commit may assist in understanding what we are looking to accomplish.

Also, Bootstrap has this baked in but it's not working on our end for some reason. https://getbootstrap.com/docs/4.0/utilities/embed/#aspect-ratios

Reference to issue - https://github.com/blockstack/blockstack.org/issues/309

**Comment by estermer** [comment]
**Weekend:** Nothing
**Today:** Nothing
