### ISSUE TITLE
design standup - Tue, Aug 22, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#406]
**Yesterday:** Discussed standup process
**Today:** Looking through the design file formats and seeing which file types I can remove from the list in the design contrib guide

**Comment by guylepage3** [comment]
_**yeseterday**_: 
- [x] Worked on live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)
- [x] Weekly sprint meeting
- [x] Browser sprint meeting
- [x] worked on browser design

_**today**_:


_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#406: design standup – Tue, Aug 22, 2017](https://github.com/blockstack/designs/issues/406)

**Comment by arisgk** [comment]
**Yesterday** Worked on tutorial videos aspect ratio.
**Today** Nothing.
