### ISSUE TITLE
design standup – Wed, Aug 23, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#407]
_**yesterday**_: 
- [x] [Worked on browser design](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Major update to http://forum.blockstack.org UI. Found quite a few breakages in;
    - [x] Dropdowns
    - [x] Navbars
    - [x] code tags
    - [x] buttons - incld. `:hover`, `:active` states
    - [x] forms
- [x] Assisted @pstan26 with Signature Bounties promo card design

_**today**_:
- [x] [Continue working on browser design for presenting tomorrow](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Review @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [x] Reviewed and merged @estermer's [README pull request/fix](https://github.com/blockstack/blockstack.org/pull/379)
- [x] Assist @pstan26 with Signature Bounties promo card design

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#407: design standup – Wed, Aug 23, 2017](https://github.com/blockstack/designs/issues/407)

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by estermer** [comment]
**Yesterday:** I looked into the Git LFS and how it works on our end to work out the process for walking contributors through using Git LFS with our design repo.

**Today:** looking over responses to questions about considered Git LFS process.
