### ISSUE TITLE
design standup – Thu, Aug 24, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#408]
_**yesterday**_: 
- [x] [Worked on browser design](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Review @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [x] Reviewed and merged @estermer's [README pull request/fix](https://github.com/blockstack/blockstack.org/pull/379)
- [x] Assist @pstan26 with Signature Bounties promo card design

_**today**_:
- [x] Sync up with @larrysalibra on browser
- [ ] [Finalize browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#408: design standup – Thu, Aug 24, 2017](https://github.com/blockstack/designs/issues/408)

**Comment by arisgk** [comment]
**Yesterday** Nothing.
**Today** I plan to apply requested changes to video aspect ratio PR.

**Comment by estermer** [comment]
**Yesterday:** Talked about the Git LFS process, determined how we may want contributors to use it

**Today:** Nothing, helped my sister move and worked from home for my job
