### ISSUE TITLE
design standup - Fri, Aug 25, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#409]
**Yesterday:** Nothing
**Today:** build out the Git LFS process for the contrib guidelines. review previous requests on design contrib guide. looking further into angular2 for generator.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Sync up with @larrysalibra on browser
- [x] [Worked on browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)

_**today**_:
- [ ] [Finalize browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#409: design standup –Fri, Aug 25th, 2017](https://github.com/blockstack/designs/issues/409)

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing
