### ISSUE TITLE
design standup – Mon, Aug 28, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#411]
_**friday**_: 
- [x] [Worked on the browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799). 
    - [x] Caught quite a few additional design issues in the edit profile section. Had to rethink and adjust layouts.

_**saturday**_: 
- [x] [Worked on the browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799). 
    - [x] Caught more additional design issues in the edit profile section.
    - [x] Design research - Reviewed numerous wallets for redesign

_**sunday**_: 
- [x] [Worked on the browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799).
    - [x] Caught more additional design issues in the edit profile section.
    - [x] Tidying up spacing.

_**today**_:
- [x] [Finalize browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [x] [Relink all designs in InVision for UX review](https://github.com/blockstack/blockstack-browser/issues/701)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#411: design standup – Mon, Aug 28, 2017](https://github.com/blockstack/designs/issues/411)

**Comment by estermer** [comment]
**Weekend and Friday:** Nothing
**Today:** Nothing for one more day and then I am back at it tomorrow.

**Comment by arisgk** [comment]
**Friday** Nothing
**Today** Nothing
