### ISSUE TITLE
design standup – Tue, Aug 29, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#412]
_**yesterday**_: 
- [x] [Worked on browser designs](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)

_**today**_:
- [x] Sync up / front end meeting with @larrysalibra @shea256 @yknl
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#412: design standup – Tue, Aug 29, 2017](https://github.com/blockstack/designs/issues/412)

**Comment by estermer** [comment]
**Yesterday:** joined the conversation about the cross platform development with cordova or just writing native code like react native. Also made sure the changes were applied to the git lfs process in the contrib guide for another review.

**Today:** Keeping an eye out for any reviews of the designs contrib guide from @guylepage3 and others. Will work a little more on the Angular 2 generator. Going to look into some bug fixes for either the browser or .org

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by guylepage3** [comment]
@estermer I will take a look at the contribution guide this evening..
