### ISSUE TITLE
design standup – Wed, Aug 30, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#414]
_**yesterday**_: 
- [x] [Worked on browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [x] Sync up / front end meeting with @larrysalibra @shea256 @yknl 
- [x] Interviewed Azeem
- [x] Started implementation of new browser design

_**today**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#414: design standup – Wed, Aug 30, 2017](https://github.com/blockstack/designs/issues/414)

**Comment by estermer** [comment]
**Yesterday:** ironed out Git LFS process and made it up to date to the current review of it. 
** Today:** going to keep an eye on @guylepage3 review of contrib process and look into bugs in either browser or .org

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Submit changes on video aspect ratio PR
