### ISSUE TITLE
design standup – Thu, Aug 31, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#416]
_**yesterday**_: 
- [x] Pulled in Bootstrap v4
- [x] Started implementation of new browser design

_**today**_:
- [ ] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- Implementation of new browser design
    - [ ] [ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
    - [ ] [ui build colors from new browser design](https://github.com/blockstack/blockstack-browser/issues/713)
    - [ ] [ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)

_**ahead**_:
- [ ] [ui build new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#416: design standup – Thu, Aug 31, 2017](https://github.com/blockstack/designs/issues/416)

**Comment by arisgk** [comment]
**Yesterday** Pushed requested changes for video aspect ratio PR.
**Today** Nothing

**Comment by yknl** [comment]
Yesterday:
- Synced up with frontend team on browser redesign
- Created design mockups for social proof verification on new browser design
- Worked on social proof verification in blockstack.js

Today:
- Work on social proof verification blockstack.js
