### ISSUE TITLE
design standup – Fri, Sep 1, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#417]
_**yesterday**_: 
- [x] Reviewed and merged @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365)
- [x] Started reviewing and working on Designs repo contribution guidelines w/@estermer
- [x] Worked with @estermer on new FAQ page design/implementation
- [x] Casual meeting with @shea256 @larrysalibra @yknl 
- [x] Started work on button implementation of new browser design

_**today**_:
- [x] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- Implementation of new browser design
    - [ ] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
    - [x] [ui build colors from new browser design](https://github.com/blockstack/blockstack-browser/issues/713)
    - [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
- [x] 1-on-1 with @yknl 
- [x] Quick sync up with @larrysalibra before he leaves.

_**ahead**_:
- [ ] [ui build new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#417: design standup – Fri, Sep 1, 2017](https://github.com/blockstack/designs/issues/417)

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by estermer** [comment]
**Yesterday:** start the process of translating the api.onename.com layout over to the FAQ page for blockstack.org.

**Today:** nothing labor day weekend trip to Upstate NY

**Comment by yknl** [comment]
Yesterday:
- Worked on implementing html/meta tag checks for social verification in blockstack.js
- Worked on adding Instagram account verification
- Synced with Larry on test cases for social verification
- 1-on-1 with Muneeb, Jude and Patrick
- Frontend team casual meeting

Today:
- Update test cases for social verification in blockstack.js
- 1-on-1 with Ryan, Gina, Guy, Aaron
- Work on browser design implementation with Guy
