### ISSUE TITLE
design standup – Tue, Sep 5, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#418]
_**friday**_: 
- [x] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- Implementation of new browser design
    - [ ] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
    - [x] [ui build colors from new browser design](https://github.com/blockstack/blockstack-browser/issues/713)
    - [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
    - [x] Cleaned up `app.css`
- [x] 1-on-1 with @yknl 
- [x] Quick sync up with @larrysalibra before he leaves.

_**today**_:
 - [x] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
- [x] [ui build new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [x] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- Start on page cleanup
    - [x] Finalize ui build of wallet
    - [ ] Finalize ui build of sidebars
- [x] add more articles to the appearances list

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#418: design standup – Tue, Sep 5, 2017](https://github.com/blockstack/designs/issues/418)

**Comment by estermer** [comment]
**Labor Day Weekend:** Nothing
**Today:** continue working on the FAQ's page layout

**Comment by yknl** [comment]
Friday + weekend:
- Add Instagram account verification
- Add Hacker News account verification
- UI build forms in browser redesign

Today:
- Browser - Pull sidebar in profiles out to separate page for redesign
- Add LinkedIn account verification

**Comment by arisgk** [comment]
**Friday & Weekend** Nothing
**Today** Nothing
