### ISSUE TITLE
design standup – Wed, Sep 6, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#422]
_**yesterday**_: 
- [x] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
- [x] [Worked on UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [x] [Finalized ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- Start on page cleanup
    - [x] Worked on ui build of wallet
    - [ ] Finalize ui build of sidebars
- [x] add more articles to the appearances list

_**today**_:
- [x] [Finalize UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- Page cleanup
    - [x] Finalize UI build of wallet
    - [x] Finalize UI build of sidebars
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#422: design standup – Wed, Sep 6, 2017](https://github.com/blockstack/designs/issues/422)

**Comment by yknl** [comment]
*Yesterday*

- Browser redesign structural changes - moved sidebars in profile and settings view into its own view

*Today*

- Work on browser redesign UI build - add new nav bar and secondary nav bars.
- Other structural changes as necessary
- Add LinkedIn social verification

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing
