### ISSUE TITLE
design standup – Thu, Sep 7, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#423]
_**yesterday**_: 
- [x] [Finalized UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- Page cleanup
    - [x] Finalized UI build of wallet
    - [x] Finalized UI build of sidebars
    - [x] Started working on UI build of settings

_**today**_:
- Page cleanup
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#423: design standup – Thu, Sep 7, 2017](https://github.com/blockstack/designs/issues/423)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Nothing

**Comment by yknl** [comment]
**Yesterday**

- Worked on browser redesign build - secondary nav bar component, updated the profile view

**Today**

- Continue to work on browser redesign build - update the all avatars view in profile, build out the main nav
- Add LinkedIn account verification to blockstack.js

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing
