### ISSUE TITLE
design standup – Fri, Sep 8, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#424]
_**yesterday**_: 
- [x] Figured out new sub-feature method in `git flow`
- [x] Worked with new designer Ben Dunkle to bring him up to speed with contributing design to Blockstack.
- [x] Met with Patrick and Zach on Berlin event
- Page cleanup
    - [x] Worked UI build of settings

_**today**_:
- Page cleanup
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#424: design standup – Fri, Sep 8, 2017](https://github.com/blockstack/designs/issues/424)

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by yknl** [comment]
**Yesterday**

- Sync up with frontend team on git flow branching issues
- Added support for LinkedIn account verification to blockstack.js
- Browser redesign build - Updated all avatars view

**Today**

- Browser redesign build - View profiles page, various pieces in profile and avatars page
