### ISSUE TITLE
design standup – Mon, Sep 11, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#425]
_**friday, saturday, sunday**_: 
- [x] Worked on UI build of navbars. Ran into issues with new navigation system from Bootstrap 4
- [x] Added items to new design system to document design items as we build to allow for more contributions/contributors.

_**today**_:
- Page cleanup
    - [x] Finalize UI build of navbars
    - [ ] [Clean up wallet view](https://github.com/blockstack/blockstack-browser/issues/743)
    - [ ] Finalize UI build of avatars w/@yknl
    - [ ] Finalize UI build of settings headers and storage
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#425: design standup – Mon, Sep 11, 2017](https://github.com/blockstack/designs/issues/425)

**Comment by yknl** [comment]
**Friday + Weekend**
- Investigate and fix blockstack.org navigation issue 
- Update avatars view for browser redesign
- Update profile view social proofs for browser redesign

**Today**
- Revise interface of `validateProofs` in blockstack.js
- Document changes to blockstack.js
- Continue to work on UI build for browser redesign

**Comment by arisgk** [comment]
**Friday** Nothing
**Today** Nothing

**Comment by estermer** [comment]
**Friday:** Worked on the FAQ page layout
**Today:** Continuing to work on the FAQ page Layout
