### ISSUE TITLE
design standup – Thu, Sep 14, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#429]
_**monday, tuesday, wednesday**_: 
- Was under the weather from Monday afternoon, Tuesday, Wednesday.. But managed to get the following done;
- [x] Finalized UI build of navbars on browser
- [x] Reviewed browser with @yknl 
- [x] Reviewed Berlin items with @pstan26 
- [x] Reviewed and replied to Ben's, Aris' and Eric's issues
- [x] Reviewed and merged @estermer's blockstack.org fix https://github.com/blockstack/blockstack.org/pull/389
- [x] [Clean up wallet view](https://github.com/blockstack/blockstack-browser/issues/743)

_**today**_:
- [x] [Signature Berlin tasks](https://github.com/blockstack/designs/issues/421) & coordination with designer for files for @pstan26 
    - [x] Print production on the chosen "Signature Berlin" logo that that the designer provided.
    - [x] Use opaque Berlin city background with newly created logo in foreground to create eventbrite image 
- Finalize browser for release to a 90-95%
    - [x] Secondary nav review - (review all states) - https://github.com/blockstack/blockstack-browser/issues/763
    - [ ] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
    - [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
    - Settings cleanup - 
        - [ ] Storage live design
    - [ ] "All Avatars" style clean up
    - [ ] On-boarding touch up
    - [ ] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
    - [ ] Check all active states
    - [ ] Check all forms

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#429: design standup – Thu, Sep 14, 2017](https://github.com/blockstack/designs/issues/429)

**Comment by yknl** [comment]
**Yesterday**
- Finish up API changes for `validateProofs` in blockstack.js
- Fix minor browser redesign UI issues, nav bar flickering
- Resolve conflicts and merge `feature/redesign` and `develop` branch in `blockstack-browser`
- Finish setting up `blockstack-explorer` and familiarize with the code base

**Today**
- Work on `blockstack-explorer` updates
- Investigate and fix issues in `blockstack-browser` redesign
- Minor change of social proof verification text in `blockstack.js`

**Comment by estermer** [comment]
**Yesterday:**Took some time to learn sketch a little and create some symbols for the sidebar to play around with different styles on the FAQ layout.
**Today:** will continue to play with the FAQ layout in sketch just a little.

**Comment by kkomaz** [comment]
**Yesterday**:
Worked on the account deletion confirmation step.

**Today**:
Get some feedback regarding this issue and will make additional fixes as needed.

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** I plan to update funding page to use `EmbedYouTube` component.
