### ISSUE TITLE
design standup – Fri, Sep 15, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#430]
_**yesterday**_: 
- [x] [Signature Berlin tasks](https://github.com/blockstack/designs/issues/421) & coordination with designer for files for @pstan26 
    - [x] Print production on the chosen "Signature Berlin" logo that that the designer provided.
    - [x] Use opaque Berlin city background with newly created logo in foreground to create eventbrite image 
- [x] [Secondary nav review - (review all states)](https://github.com/blockstack/blockstack-browser/issues/763) on browser
- [x] [Started on main avatar review](https://github.com/blockstack/blockstack-browser/issues/764)
- [x] Token designer coordination
- [x] Reviewed a couple of Alex's pull requests as well as Aris and Eric's PR's.
- [x] Started audit of frontend engineering of browser and created issues - Working state of browser is not at 100%.

_**today**_:
- [x] Sync up with @larrysalibra & @yknl 
- [x] Token frontend meeting with @MechanicalHuman & @pstan26 
- [ ] Provide details for webkit native window to mobile size and look for @larrysalibra 
- [ ] Setup regtest - https://github.com/blockstack/blockstack-core/blob/master/docs/interactive_regtest_macos.md
- [x] Review and feedback on @estermer's [integrate ui from api.onename.com for FAQ section of blockstack.org](https://github.com/blockstack/blockstack.org/issues/380#issuecomment-329827933)
- [x] Review and merge @arisgk's [update funding page to use EmbedYouTube component pull request](https://github.com/blockstack/blockstack.org/pull/391#pullrequestreview-63110327)

Finalize browser for release to a 90-95%
- [x] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
- [x] add border to all input fields on default forms - https://github.com/blockstack/blockstack-browser/issues/780
- [x] Review all forms - https://github.com/blockstack/blockstack-browser/issues/774
- [ ] Storage live design - https://github.com/blockstack/blockstack-browser/issues/772
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [x] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
- [ ] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [ ] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [ ] Final audit of frontend engineering of browser

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#430: design standup – Fri, Sep 15, 2017](https://github.com/blockstack/designs/issues/430)

**Comment by estermer** [comment]
**Yesterday:** nothing
**Today:** just discussing some things about the styles for the faq layout to tackle some work over the weekend

**Comment by arisgk** [comment]
**Yesterday** Worked on funding page video component. Submitted https://github.com/blockstack/blockstack.org/pull/391 PR.

**Today** Nothing

**Comment by guylepage3** [comment]
@arisgk @estermer I'll comment on issues now. 😄

**Comment by kkomaz** [comment]
**Yesterday**
Added a cursor pointer for button and a tags.  Also fixed ui change requests on delete account confirmation

**Today**
Nothing

**Comment by guylepage3** [comment]
thanks for your help @kkomaz. will be merging your stuff in over the weekend. 😄
