### ISSUE TITLE
design standup – Mon, Sep 18, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#431]
_**friday, saturday, sunday**_: 
- [x] Sync up with @larrysalibra & @yknl 
- [x] Token frontend meeting with @MechanicalHuman & @pstan26 
- [x] Review and feedback on @estermer's [integrate ui from api.onename.com for FAQ section of blockstack.org](https://github.com/blockstack/blockstack.org/issues/380#issuecomment-329827933)
- [x] Review and merge @arisgk's [update funding page to use EmbedYouTube component pull request](https://github.com/blockstack/blockstack.org/pull/391#pullrequestreview-63110327)
- [x] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
- [x] add border to all input fields on default forms - https://github.com/blockstack/blockstack-browser/issues/780
- [x] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
- [x] Review all forms - https://github.com/blockstack/blockstack-browser/issues/774
- [x] Provide details for webkit native window to mobile size and look for @larrysalibra - https://github.com/blockstack/blockstack-browser/issues/697
- [x] Storage live design - https://github.com/blockstack/blockstack-browser/issues/772

_**today**_:
- [x] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [x] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [x] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [x] add navbar & secondary nav margin bottom - https://github.com/blockstack/blockstack-browser/issues/786
- [x] Review and merge @kkomaz's pull request - [Change remove account button to red](https://github.com/blockstack/blockstack-browser/pull/753)
- [x] Review and merge @kkomaz's pull request - [Account delete confirmation step modal create](https://github.com/blockstack/blockstack-browser/pull/760)
- [x] Review and merge @kkomaz's pull request - [Add cursor pointer to button and a tags](https://github.com/blockstack/blockstack-browser/pull/771)
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [x] Priority! Setup regtest - https://github.com/blockstack/blockstack-browser/issues/795
- [ ] Final audit of frontend engineering of browser

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#431: design standup – Mon, Sep 18, 2017](https://github.com/blockstack/designs/issues/431)

**Comment by arisgk** [comment]
**Friday & Weekend** Nothing
**Today** Nothing

**Comment by kkomaz** [comment]
**Friday & Weekend** Nothing
** Today **: Nothing.  @guylepage3 let me know if there's anything near EOD on the feature/redesign that you guys couldn't get to that might need assistance on.  I'll let you know if I can get to it :)

**Comment by yknl** [comment]
**Fri + Weekend**
- Sync with @larrysalibra & @guylepage3 on browser
- Worked on browser issues - "Add Username" button, owner address tooltip, edit button bug, add back button to on-boarding identity key page

**Today**
- Attend to browser issues as they arise
- Work on switching `blockstack-explorer` to blockstack core api

**Comment by guylepage3** [comment]
> @guylepage3 let me know if there's anything near EOD on the feature/redesign that you guys couldn't get to that might need assistance on. I'll let you know if I can get to it 😄

@kkomaz will do for sure. thank you for the offer sir. 👍
