### ISSUE TITLE
design standup – Tue, Sep 19, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#433]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [x] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [x] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [x] add navbar & secondary nav margin bottom - https://github.com/blockstack/blockstack-browser/issues/786
- [x] Review and merge @kkomaz's pull request - [Change remove account button to red](https://github.com/blockstack/blockstack-browser/pull/753)
- [x] Review and merge @kkomaz's pull request - [Account delete confirmation step modal create](https://github.com/blockstack/blockstack-browser/pull/760)
- [x] Review and merge @kkomaz's pull request - [Add cursor pointer to button and a tags](https://github.com/blockstack/blockstack-browser/pull/771)
- [x] Priority! Setup regtest - https://github.com/blockstack/blockstack-browser/issues/795

_**today**_:
- [x] Review and merge @jackzampolin's pull request - https://github.com/blockstack/blockstack.org/pull/390
- [x] Blog image
- [x] Event video asset production
- [x] Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [ ] Final audit of frontend engineering of browser
- [ ] Start on blockstack.org review

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#433: design standup – Tue, Sep 19, 2017](https://github.com/blockstack/designs/issues/433)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Nothing, busy at work this week

**Comment by yknl** [comment]
**Yesterday**
- Fix set default profile bug in browser
- Fix nav state issue in browser
- Setup Insight API on bitcore node for @jackzampolin
- Setup regtest with help from @kantai and test name registration in browser

**Today**
- Resolve any remaining browser issues
- Work on switching explorer to use blockstack-core api

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing

**Comment by kkomaz** [comment]
**Yesterday**
Worked on ToolTip default placement.
https://github.com/blockstack/blockstack-browser/pull/800

**Today**
Will attempt to set up docker test environment

**Comment by freethejazz** [comment]
**Yesterday**
Chore regarding updating stale references to `blockstack-portal`

**Today**
Looking into blockstack/blockstack-browser#784
