### ISSUE TITLE
design standup – Wed, Sep 20, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#436]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Review and merge @jackzampolin's pull request - https://github.com/blockstack/blockstack.org/pull/390
- [x] Blog image
- [x] Event video asset production
- [x] Spent time recruiting more developers, providing them with tasks and on-boarding

_**today**_:
- [x] Blockstack.org meeting with @muneeb-ali & @GinaAbrams 
- [ ] ~~Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803~~ - passed over to @yknl 
- [ ] ~~Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690~~ - passed over to @yknl 
- [ ] ~~On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651~~ - passed over to @yknl 
- [ ] ~~Final audit of frontend engineering of browser~~ - passed over to @yknl 
- [ ] Start on blockstack.org design and build

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#436: design standup – Wed, Sep 20, 2017](https://github.com/blockstack/designs/issues/436)

**Comment by yknl** [comment]
**Yesterday**
- Work on setting up blockstack-explorer to use the core api

**Today**
- Continue working on blockstack-explorer, replace explorer API endpoints with core endpoints

**Comment by kkomaz** [comment]
**Yesterday**
- Setup test environment.
- Rebased https://github.com/blockstack/blockstack-browser/pull/800 and ready for Review

**Today**
- Fix Search Button color https://github.com/blockstack/blockstack-browser/issues/802
- Make form inputs more viewable https://github.com/blockstack/blockstack-browser/issues/801

**Todo**
- Nothing on the board that I probably cant complete tonight.

**Comment by freethejazz** [comment]
**Yesterday**
- resolved an open question regarding implementation of blockstack/blockstack-browser#784

**Today**
- likely nothing

**Todo**
- create a reusable `EllipsizedText` component via a CSS approach blockstack/blockstack-browser#784
- Backport that fix to the SocialItem component

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org

**Comment by estermer** [comment]
**Yesterday:**

Looked over the contributing guide for blockstack.org in regards to linking issues to the PR and commented on the ticket

**Today:**

Nothing

**Ahead:** 

- FAQ's layout
- Contributing Guide for blockstack.org
- Contributing Guide for designs
- Vue.js/Angular 2 Generators
