### ISSUE TITLE
design standup – Thu, Sep 21, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#439]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Blockstack.org meeting with @muneeb-ali & @GinaAbrams - pulled from browser work to work on blockstack.org and token deliverables.
- [ ] ~~Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803~~ - passed over to @yknl 
- [ ] ~~Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690~~ - passed over to @yknl 
- [ ] ~~On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651~~ - passed over to @yknl 
- [ ] ~~Final audit of frontend engineering of browser~~ - passed over to @yknl 
- [x] Browser sync up with @yknl to hand off browser work
- [x] Managed community members and assigned tasks
- [x] Started on blockstack.org design research
- [x] Update to PBC blog post image
- [x] Worked with @zachvalenti and @pstan26 on the positioning of assets for the berlin video
- [x] blockstack meetup q&a video template - https://github.com/blockstack/designs/issues/438
- Left early will make up time on weekend.

_**today**_:
❗️**Currently blocked** ❗️
- [ ] Continue on blockstack.org design / build once deliverables have been signed off on.

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#439: design standup – Thu, Sep 21, 2017](https://github.com/blockstack/designs/issues/439)

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org

**Comment by kkomaz** [comment]
**Yesterday**

- Fix Search Button bg coloring issue https://github.com/blockstack/blockstack-browser/pull/812

**Today**
- Got some feedback regarding sizing and best practices for buttons.  Will create an issue and make a fix for it.

**Ahead**
- Going to take a break for a few days.
- @arisgk Let me know if you want to tackle some component based testing via Enzyme and Jest.  That would be awesome 😄

**Comment by freethejazz** [comment]
**Yesterday**
- squadoosh

**Today**
- build/test the `ElipsizedText` component

**Todo**
- Backport that fix to the `SocialAccountItem` component

**Comment by yknl** [comment]
**Yesterday**
- Work on blockstack-explorer, started replacing API endpoints with core endpoints
- Adjust blockstack-browser max-width for optimal display on wider screens
- Designed new on-boarding icons and updated welcome modal
- Fixed modal form margin issues
- Audit of browser for release

**Today**
- Fix browser bug where no default profile is set after restore profile
- Update the photo upload UI in browser for redesign
- Work on blockstack-explorer

**Comment by vicnicius** [comment]
**Yesterday**

- Nothing

**Today**

- Setup dev environment

**Todo**
- Look for the first issue to work on

**Comment by estermer** [comment]
**Yesterday:**

Looked over the contributing guide for blockstack.org in regards to linking issues to the PR and commented on the ticket

**Today:**

Nothing

**Ahead:** 

- FAQ's layout
- Contributing Guide for blockstack.org
- Contributing Guide for designs
- Vue.js/Angular 2 Generators
