### ISSUE TITLE
design standup – Fri, Sep 22, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#440]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Blockstack.org & UI design research
- [x] Managed community members and assigned tasks
- [x] Blockstack.org meeting `#2` w/@muneeb, @larrysalibra, @shea256, @GinaAbrams 
- [x] Started [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] Started [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Blockstack Meetup Q&A video template - https://github.com/blockstack/designs/issues/438

_**today**_:
- [x] Review browser design issues and community member responses
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#440: design standup – Fri, Sep 22, 2017](https://github.com/blockstack/designs/issues/440)

**Comment by yknl** [comment]
**Yesterday**
- Fix browser bug where no default profile is set after restore profile
- Final review of browser for release
- 1 on 1 with @larrysalibra 
- Work on explorer updates

**Today**
- Meeting with @shea256 @larrysalibra  for KYC/AML API
- Finish update on blockstack explorer to use core api
- Update explorer address page to list profile cards

**Todo**
- Move explorer to id.blockstack.org
- Add new endpoint to explorer
- Use core api search in explorer
- Show potentially valid blockstack transactions in current blocks in explorer
- Update browser social verifications UX
- KYC/AML API

**Comment by kkomaz** [comment]
**Yesterday**
Fix Search and Cancel Button styles related to username search/registration

**Today**
Nothing

**Todo**
Add absolute path support via https://github.com/blockstack/blockstack-browser/issues/825

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
