### ISSUE TITLE
design standup - Mon Sept 25, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#443]
**Last Week:** Nothing, took some time to crank down some stuff at work before returning to contributions

**Today:** going to checkout any further work needed on the FAQ layout

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**Friday/Saturday/Sunday**_: 
- [x] Review browser design issues and community member responses
- [x] [token portfolio manager bounty images for email and eventbrite](https://github.com/blockstack/designs/issues/437)
- [x] Took a Sublime Text 3 full day course to increase productivity

_**today**_:
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#443: design standup – Mon, Sep 25, 2017](https://github.com/blockstack/designs/issues/443)

**Comment by guylepage3** [comment]
@estermer let's chat about the FAQ as they are now a priority for the blockstack.org update.

**Comment by yknl** [comment]
**Last week**
- Fix blockstack-browser issues and get it ready for release
- Meetings to sync up on frontend tasks
- Complete implementation of core API use in blockstack-explorer
- Added profile list to explorer address page

**Today**
- Test blockstack-explorer updates
- Start working on blockstack-browser social proof verifications

**Comment by kkomaz** [comment]
**Friday**
Nothing

**Today**
Add absolute path support via blockstack/blockstack-browser#825

**Todo**
Nothing  on the docket but will look around.

**Comment by arisgk** [comment]
**Friday & Weekend**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org

**Comment by vicnicius** [comment]
**Friday & Weekend**

Got my environment setup properly.

**Today**

Nothing

**Ahead**

- Studying: connecting the whitepaper concepts with the actual code
- Look for some JS issues around
