### ISSUE TITLE
design standup – Tue, Sep 26, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#444]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Worked with @estermer on [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] Worked on [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Worked on [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
- Ran into issues with npm installation that kept reverting back from Bootstrap v4 to old alpha version without knowledge. Would end up resolving issues on both versions.
- Had to go home early and lost quite a bit of the day.

_**today**_:
- [x] [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
- [x] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#444: design standup – Tue, Sep 26, 2017](https://github.com/blockstack/designs/issues/444)

**Comment by estermer** [comment]
**Yesterday:** Finishing touches on the FAQ Layout
**Today:** Merged in @guylepage3 s updates in `feature/bootstrap` and submitting a PR.

@guylepage3 would you like me to create an issue for integrating the FAQ layout to the DOC's page

**Comment by guylepage3** [comment]
>@guylepage3 would you like me to create an issue for integrating the FAQ layout to the DOC's page

@estermer Yes please sir.. 😄

**Comment by yknl** [comment]
**Yesterday**
- Test blockstack-explorer updates, fixed issues
- Diagnose & fix issues in blockstack.org site

**Today**
- Finish testing + review of blockstack-explorer updates
- Update explorer in production
- Start working on blockstack-browser social proof verifications

**Comment by freethejazz** [comment]
**Yesterday**
Nothing

**Today**
- Initial pass at blockstack/blockstack-browser#784

**Ahead**
- Apply those changes to other `blockstack-browser` components that ellipsize text
