### ISSUE TITLE
design standup – Wed, Sep 27, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#445]
**Yesterday:** Submitted 2 PR's to the `feature/bootstrap` base on blockstack.org for the FAQ and  Docs pages that now implement the ui from onename's api docs.

**Today:** going to keep an eye on any feed back regarding the PR's

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**Friday/Saturday/Sunday**_: 
- [x] Worked with @estermer on [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
  - Ran into issues with npm installation that kept reverting back from Bootstrap v4 to old alpha version without knowledge. Would end up resolving issues on both versions.
- [x] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Started [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)

_**today**_:
- [ ] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#445: design standup – Wed, Sep 27, 2017](https://github.com/blockstack/designs/issues/445)
