### ISSUE TITLE
design standup – Thu, Sep 28, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#446]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] [#418: Add Windows Browser link to install page](https://github.com/blockstack/blockstack.org/issues/418)
- [x] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)

_**today**_:
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] Work on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)
- [ ] Go through entire site and make sure sections are consistent

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#446: design standup – Thu, Sep 28, 2017](https://github.com/blockstack/designs/issues/446)

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
