### ISSUE TITLE
design standup – Fri, Sep 29, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#447]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [x] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] Review, merge and touch-up [#417: Integrate ui from api.onename.com to Docs page](https://github.com/blockstack/blockstack.org/pull/417)
- [x] Touched and rebuilt structure on all pages/sections of blockstack.org other than;
  - sign-up
  - funding
  - press
  - press pre-footer
  - intro
  - careers
  - career link
  - 404 page
  - See components and pages list here [›› Complete list](https://github.com/blockstack/blockstack.org/issues/399)

_**today**_:
- [x] Finalize [#415: Live design new footer](https://github.com/blockstack/blockstack.org/issues/415)
- [x] [#424: Restructure funding page](https://github.com/blockstack/blockstack.org/issues/424)
- [x] [#427: Update home page layout](https://github.com/blockstack/blockstack.org/issues/427)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)

_**ahead**_:
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#447: design standup – Fri, Sep 29, 2017](https://github.com/blockstack/designs/issues/447)

**Comment by yknl** [comment]
**Yesterday**
- Address explorer issues from larry's feedback on the PR
- Fix bug in browser, where profile isn't displayed when logging into apps
- Work on implementation of new social proof verification UX

**Today**
- Work on implementation of new social proof verification UX

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Going to start some work on integrating blockstack.js and core into the new docs layout
