### ISSUE TITLE
design standup – Mon, Oct 2, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#449]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**friday, saturday, sunday**_: 
- [x] Finalize [#415: Live design new footer](https://github.com/blockstack/blockstack.org/issues/415)
- [x] [#424: Restructure funding page](https://github.com/blockstack/blockstack.org/issues/424)
- [x] [#427: Update home page layout](https://github.com/blockstack/blockstack.org/issues/427)

_**today**_:
- [x] [#430: Live design new dropdown menu](https://github.com/blockstack/blockstack.org/issues/430) on blockstack.org
- [x] [#450: Design new placeholder image for blockstack.org home page video](https://github.com/blockstack/designs/issues/450)
- [x] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)

_**ahead**_:
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#449: design standup – Mon, Oct 2, 2017](https://github.com/blockstack/designs/issues/449)

**Comment by arisgk** [comment]
**Friday & Weekend**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
