### ISSUE TITLE
design standup – Tue, Oct 3, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#451]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Weekly scrum
- [x] Frontend meeting
- [x] [#430: Live design new dropdown menu](https://github.com/blockstack/blockstack.org/issues/430) on blockstack.org
- [x] [#450: Design new placeholder image for blockstack.org home page video](https://github.com/blockstack/designs/issues/450)
- [x] Had issues with the [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416). Had to pass off to @yknl.

_**today**_:
- [x] Front-end meeting
- [x] [#453: Quick design of new "Initial Profile Landing View"](https://github.com/blockstack/designs/issues/453)
- [x] Created Sketch license key for @yknl 
- [x] [#431: Resolve mobile navbar dropdown](https://github.com/blockstack/blockstack.org/issues/431) on blockstack.org
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)

_**ahead**_:
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#451: design standup – Tue, Oct 3, 2017](https://github.com/blockstack/designs/issues/451)

**Comment by kkomaz** [comment]
**Yesterday**
Nothing

**Today**
Nothing

**Ahead**
Busy again this week.  Hopefully free up next week!

**Comment by yknl** [comment]
**Yesterday**
- Frontend sync up
- Work on new social proof verification in browser
- Add ability to use custom preview images on blockstack.org videos

**Today**
- Work on new social proof verification in browser
- Get new explorer version up and running
