### ISSUE TITLE
design standup – Wed, Oct 4, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#457]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Front-end meeting
- [x] [#453: Quick design of new "Initial Profile Landing View"](https://github.com/blockstack/designs/issues/453)
- [x] Created Sketch license key for @yknl 
- [x] [#431: Resolve mobile navbar dropdown](https://github.com/blockstack/blockstack.org/issues/431) on blockstack.org

_**today**_:
- [x] Blockstack.org meeting for new content
- [x] [#456: Create quick brand banner](https://github.com/blockstack/designs/issues/456)
- [x] Review browser issues
- [x] [#432: Resolve blockstack.org breakages](https://github.com/blockstack/blockstack.org/issues/432) that occurred during lsat night's merge
- [x] [#455: Design new frame and background for browser](https://github.com/blockstack/designs/issues/455)
- [ ] [#433: Live design new multi-video player for all 4 views](https://github.com/blockstack/blockstack.org/issues/433)
- [ ] [#435: Live design new home page whitepaper section](https://github.com/blockstack/blockstack.org/issues/435)
- [ ] [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [ ] [#459: Design two new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)

_**ahead**_:
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#457: design standup – Wed, Oct 4, 2017](https://github.com/blockstack/designs/issues/457)

**Comment by yknl** [comment]
**Yesterday**
- Frontend meeting
- Work on new social proof verification in browser
- Get new explorer version up and running @ explorer.blockstack.org

**Today**
- Work on browser social proof verifications
- Browser improvements for release https://github.com/blockstack/blockstack-browser/issues/844

**Todo**
- Browser improvements for release

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
