### ISSUE TITLE
Design two PDF cover pages for token whitepapers

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#458]
Design two PDF cover pages for token whitepapers.

**Tasks**
- [x] Design "Blockstack Technical Whitepaper " cover page - 8.5 x 11 
  - [x] Content (Headline & copy) to come from @muneeb-ali 
  - [ ] Apply to current version of PDF
- [x] Design "Blockstack Token Whitepaper" cover page (greyed out version) - 8.5 x 11
  - [x] Content (Headline & copy) to come from @muneeb-ali 
  - [ ] Apply to current version of PDF

**Comment by guylepage3** [comment]
Design round 1...
<img width="775" alt="screenshot 2017-10-06 14 34 07" src="https://user-images.githubusercontent.com/1711854/31293102-fcc256c6-aaa3-11e7-8b9a-645d4eb471ce.png">

**Comment by guylepage3** [comment]
@muneeb-ali @shea256 The cover page and icons are ready to go once I get the copy for them.

**Comment by guylepage3** [comment]
@muneeb-ali, just a quick reminder for content on the cover pages of white papers.

**Comment by muneeb-ali** [comment]
Here is the content:

```
---------------------------------------------------------------------------------

Blockstack Technical Whitepaper 

Blockstack: A New Internet for Decentralized Applications

Muneeb Ali Ryan Shea Jude Nelson Michael J. Freedman 

https://blockstack.org 
Technical Whitepaper Version 1.1 
October 12, 2017

Footer: Copyright 2017 Blockstack PBC -- a Public Benefit Corp. All rights reserved. 

----------------------------------------------------------------------------------

Blockstack Token Whitepaper 

Stack: A Blockchain Token Mechanism for Growing an Ecosystem of Decentralized Applications 

Ryan Shea Muneeb Ali 

https://blockstack.com 
Token Whitepaper Version 1.0 
October 12, 2017

Footer: Copyright 2017 Blockstack Token LLC. All rights reserved.
---------------------------------------------------------------------------------
```

**Comment by guylepage3** [comment]
[blockstack-technical-whitepaper-cover.pdf](https://github.com/blockstack/designs/files/1377688/blockstack-technical-whitepaper-cover.pdf)
[blockstack-token-whitepaper-cover.pdf](https://github.com/blockstack/designs/files/1377689/blockstack-token-whitepaper-cover.pdf)

**Comment by guylepage3** [comment]
complete

**Comment by shea256** [comment]
Nice! Only suggestion would be to change the footer of the technical whitepaper so that instead of using two dashes "--" it uses a comma or parentheses to separate "A Public Benefit Corp.".

**Comment by muneeb-ali** [comment]
Good work, Guy! I'm trying this out now.

**Comment by guylepage3** [comment]
Update to the technical whitepaper cover as per @shea256's comments

[blockstack-technical-whitepaper-cover.pdf](https://github.com/blockstack/designs/files/1378170/blockstack-technical-whitepaper-cover.pdf)
