### ISSUE TITLE
design standup – Mon, Oct 9, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#464]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**friday**_: 
- [x] [#458: Design two PDF cover pages for token white papers](https://github.com/blockstack/designs/issues/458)
- [x] Finalize [#459: Design two new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [x] [#463: Design hard fork blog post image](https://github.com/blockstack/designs/issues/463)
- [x] [#440: Place new white paper icon on home page](https://github.com/blockstack/blockstack.org/issues/440)
- [x] [#437: Remove“Token banner” replace w/blue “pill” navbar btn](https://github.com/blockstack/blockstack.org/issues/437)

_**today**_:
- [x] [#436: Remove "Get Updates" btn & place form on bottom of page](https://github.com/blockstack/blockstack.org/issues/436)
- [x] [#226: Live design sign-up form page](https://github.com/blockstack/blockstack.org/issues/226)
- [x] [#466: Design new Home and Wallet icons for browser](https://github.com/blockstack/designs/issues/466)
- [x] [#877: Place new Home and Wallet Icons](https://github.com/blockstack/blockstack-browser/issues/877)
- [ ] ›› [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)

_**ahead**_:
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#464: design standup – Mon, Oct 9, 2017](https://github.com/blockstack/designs/issues/464)

**Comment by yknl** [comment]
**Last week**
- Social proof verifications in browser
- Clean up name purchase view in browser
- Test browser for v0.17 release

**Today**
- Review browser PRs
- Look into blank social account issue in browser
- User profile search in browser
- Edit profile redirect in browser
- Profile completion progress in browser
