### ISSUE TITLE
design standup – Tue, Oct 10, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#467]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] [#436: Remove "Get Updates" btn & place form on bottom of page](https://github.com/blockstack/blockstack.org/issues/436)
- [x] [#226: Live design sign-up form page](https://github.com/blockstack/blockstack.org/issues/226)
- [x] [#466: Design new Home and Wallet icons for browser](https://github.com/blockstack/designs/issues/466)
- [x] Major update to whitepaper section on home page of blockstack.org
- [x] [#877: Place new Home and Wallet Icons](https://github.com/blockstack/blockstack-browser/issues/877)
- [x] Worked on [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)

_**today**_:
- [x] Finalize [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)
- [x] [#468: New browser profile design](https://github.com/blockstack/designs/issues/468) from Frontend meeting
- [x] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] ›› [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.18.sketch` file

Link to today's open source design contributor standup:
- [#467: design standup – Tue, Oct 10, 2017](https://github.com/blockstack/designs/issues/467)

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
