### ISSUE TITLE
design standup – Wed, Oct 11, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#469]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
----

_**yesterday**_: 
- [x] Browser – Finalize [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)
- [x] Browser – [#468: New browser profile design](https://github.com/blockstack/designs/issues/468) from Frontend meeting
- [x] Blockstack.org – [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [x] Meeting with @shea256 on Token frontend
- [x] Blockstack.com – Worked on [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**today**_:
- [x] Blockstack.org – [#441: Add "sign-up" button back into hero on the home page](https://github.com/blockstack/blockstack.org/issues/441)
- [x] Token – [#470: Design token blog post image](https://github.com/blockstack/designs/issues/470)
- [x] Token – [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [x] Token – [#111: Update blockstack.org/token to include a token whitepaper section](https://github.com/blockstackinc/tokensale/issues/111)
- [x] Token – [#459: Design new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [ ] Token – [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421) on blockstack.org
- [ ] Token – [#109: Add disclaimer to blockstack.org](https://github.com/blockstackinc/tokensale/issues/109)
- [ ] Token – [#114: Build new privacy policy page](https://github.com/blockstackinc/tokensale/issues/114) on blockstack.com
- [ ] Token – [#108: Add disclaimer to blockstack.com](https://github.com/blockstackinc/tokensale/issues/108)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Blockstack.com – [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] Token – [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#469: design standup – Wed, Oct 11, 2017](https://github.com/blockstack/designs/issues/469)

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
