### ISSUE TITLE
design standup – Fri, Oct 13, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#474]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
----

_**yesterday**_: 
- [x] Token – [#471: Design a token whitepaper blog post button/card](https://github.com/blockstack/designs/issues/471)
- [x] Reviewed all 200+ GitHub issue notifications on Browser, Blockstack.org, Token, etc. that have been piling up over the past few days.
- [x] Onename.com – Attempted to setup python environment to resolve UI breakages on onename.com in Safari
- [x] Blockstack.com – Worked on design discovery for [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**today**_:
- [x] Browser – Meeting with @yknl to review [#473: Type & other important components are not highly visible](https://github.com/blockstack/designs/issues/473)
- [x] Blockstack.com/Coinlist meeting with @shea256 @muneeb-ali to review all deliverables.
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Blockstack.com – More design discovery for [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Token – [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#474: design standup – Fri, Oct 13, 2017](https://github.com/blockstack/designs/issues/474)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** Nothing

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
