### ISSUE TITLE
design standup – Mon, Oct 16, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#476]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
- [Coinlist](https://coinlist.co/filecoin)
----

_**friday, saturday, sunday**_: 
- [x] Browser – Meeting with @yknl to review [#473: Type & other important components are not highly visible](https://github.com/blockstack/designs/issues/473)
- [x] Blockstack.com/Coinlist meeting with @shea256 @muneeb-ali to review all deliverables.
- [x] Blockstack.com – Completed design discovery for [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)
- [x] Coinlist – Completed design discovery Coinlist distribution site
- [x] [#475: Quickly design a symbol for Stacks](https://github.com/blockstack/designs/issues/475)

_**today**_:
- [x] Blockstack.com – [#491: Design navbar for blockstack.com](https://github.com/blockstack/designs/issues/491)
- [x] Blockstack.com – [#477: Design welcome banner for blockstack.com](https://github.com/blockstack/designs/issues/477)
- [x] Blockstack.com – [#478: Design countdown timer for blockstack.com](https://github.com/blockstack/designs/issues/478)
- [x] Coinlist – [#452: Design Coinlist hero section](https://github.com/blockstack/designs/issues/452)
- [x] Blockstack.com – [#479: Design sale timeline for blockstack.com](https://github.com/blockstack/designs/issues/479)
- [x] Blockstack.com – [#480: Design video section for blockstack.com](https://github.com/blockstack/designs/issues/480)
- [x] Blockstack.com – [#481: Design whitepapers section for blockstack.com](https://github.com/blockstack/designs/issues/481)
- [x] Blockstack.com – [#482: Design legal docs section on blockstack.com](https://github.com/blockstack/designs/issues/482)
- [x] Blockstack.com – [#483: Design about Blockstack on blockstack.com](https://github.com/blockstack/designs/issues/483)
- [x] Blockstack.com – [#484: Design team & investors section on blockstack.com](https://github.com/blockstack/designs/issues/484)
- [ ] ›› Blockstack.com – [#492: Design press section for blockstack.com](https://github.com/blockstack/designs/issues/492)
- [ ] Blockstack.com – [#493: Design latest news section for blockstack.com](https://github.com/blockstack/designs/issues/493)
- [ ] Blockstack.com – [#485: Design legal disclaimer section on blockstack.com](https://github.com/blockstack/designs/issues/485)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] Coinlist – [#489: Design Coinlist press section](https://github.com/blockstack/designs/issues/489)
- [ ] Coinlist – [#490: Design Coinlist disclaimer section](https://github.com/blockstack/designs/issues/490)
- [ ] Blockstack.org – Add Token Banner back to website
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#476: design standup – Mon, Oct 16, 2017](https://github.com/blockstack/designs/issues/476)

**Comment by estermer** [comment]
**Weekend:** Nothing, started playing around with Vue.js to maybe get started on building the Vue.js app generator
**Today:** continue playing around with Vue.js will probably do this throughout the week to familiarize myself well enough to get started on the generator

**Comment by yknl** [comment]
**Last Week**
- Review and merge in trust level system
- Worked on several small browser issues
- Updates to blockstack.org and blockstack.js

**Today**
- Frontend sync
- Implement app meta data fetch in browser

**Todo**
- Browser profile updates to address user testing issues
- App sign-in UX updates
- Blockstack explorer updates
