### ISSUE TITLE
design standup – Tue, Oct 17, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#494]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
- [Coinlist](https://coinlist.co/filecoin)
- [UPDATED: Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Frontend-meeting-Oct-13-FyFo57w7gYbu5DcBh5PsJ)
----

_**yesterday**_:
- [x] Blockstack.com – [#491: Design navbar for blockstack.com](https://github.com/blockstack/designs/issues/491)
- [x] Blockstack.com – [#477: Design welcome banner for blockstack.com](https://github.com/blockstack/designs/issues/477)
- [x] Blockstack.com – [#478: Design countdown timer for blockstack.com](https://github.com/blockstack/designs/issues/478)
- [x] Coinlist – [#452: Design Coinlist hero section](https://github.com/blockstack/designs/issues/452)
- [x] Blockstack.com – [#479: Design sale timeline for blockstack.com](https://github.com/blockstack/designs/issues/479)
- [x] Blockstack.com – [#480: Design video section for blockstack.com](https://github.com/blockstack/designs/issues/480)
- [x] Blockstack.com – [#481: Design whitepapers section for blockstack.com](https://github.com/blockstack/designs/issues/481)
- [x] Blockstack.com – [#482: Design legal docs section on blockstack.com](https://github.com/blockstack/designs/issues/482)
- [x] Blockstack.com – [#483: Design about Blockstack on blockstack.com](https://github.com/blockstack/designs/issues/483)
- [x] Blockstack.com – [#484: Design team & investors section on blockstack.com](https://github.com/blockstack/designs/issues/484)

_**today**_:
- [x] Blockstack.com – Update [#484: Design team section on blockstack.com](https://github.com/blockstack/designs/issues/484) to have container element
- [x] Blockstack.com - [#495: Rethink blockstack.com hero section](https://github.com/blockstack/designs/issues/495)
- [x] Blockstack.com – [#496: Design advisors section on blockstack.com](https://github.com/blockstack/designs/issues/496)
- [x] Blockstack.com – [#497: Design investors section on blockstack.com](https://github.com/blockstack/designs/issues/497)
- [x] Blockstack.com – [#498: Design timeline for distribution section on blockstack.com](https://github.com/blockstack/designs/issues/498)
- [x] Blockstack.com – [#492: Design press section for blockstack.com](https://github.com/blockstack/designs/issues/492)
- [ ] Blockstack.com – [#493: Design latest news section for blockstack.com](https://github.com/blockstack/designs/issues/493)
- [ ] Blockstack.com – [#485: Design legal disclaimer section on blockstack.com](https://github.com/blockstack/designs/issues/485)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] Coinlist – [#489: Design Coinlist press section](https://github.com/blockstack/designs/issues/489)
- [ ] Coinlist – [#490: Design Coinlist disclaimer section](https://github.com/blockstack/designs/issues/490)
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Add Token Banner back to website
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#494: design standup – Tue, Oct 17, 2017](https://github.com/blockstack/designs/issues/494)

**Comment by yknl** [comment]
**Yesterday**
- Frontend sync
- Implement app meta data fetch in browser

**Today**
- Browser profile updates to address user testing issues
- App sign-in UX updates

**Todo**
- Blockstack explorer updates

**Comment by estermer** [comment]
**Yesterday:** Worked on getting the Hello Blockstack App generator using Vue.JS going.
**Today:** Will continue to work on that generator

**Comment by arisgk** [comment]
**Yesterday**

Nothing

**Today**

Nothing

**Ahead**

- Search for video aspect ratio issues throughout blockstack.org site.
- Organize blockstack.org `main.css` file, breaking it up into component sections.
- Add tests to blockstack.org codebase using [Enzyme](http://airbnb.io/enzyme/index.html) and [Jest](https://facebook.github.io/jest/)
- Add page-specific metadata to blockstack.org
