### ISSUE TITLE
design standup – Wed, Oct 25, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#530]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Coinlist-Blockstack.com-FyFo57w7gYbu5DcBh5PsJ)

----

_**yesterday**_:
- [x] Computer/disk space issues.
- [x] Browser – Looked into changing the icons/navbar for the browser but decided to push this off for the next release [#526: Update navbar icons to ultramarine blue & export for browser](https://github.com/blockstack/designs/issues/526)
- [x] Blockstack.com – Reviewing site and providing feedback for Barefoot
- [x] Onename – [#368: Create HTML button for Onename email](https://github.com/blockstack/blockstack/issues/368)

_**today**_:
- [x] Blockstack.com – Finalization of site and provided more feedback for Barefoot
- [x] Coinlist – [#529: Update layout of purchase to token site](https://github.com/blockstack/designs/issues/529)
- [x] Blockstack.com – [#527: Add four more investors to investor section blockstack.com](https://github.com/blockstack/designs/issues/527)
- [x] Blockstack.com – [#518: About section content update for blockstack.com](https://github.com/blockstack/designs/issues/518)
- [x] Blockstack.com – Coordination of site and provided more feedback for Barefoot
- [x] Reviewed issues on browser and blockstack.org
- [x] [#531: Produce both B & W versions of stacks logo](https://github.com/blockstack/designs/issues/531)
- [x] Blockstack.com – [#528: Add titles to all team and advisors on blockstack.com](https://github.com/blockstack/designs/issues/528)
- [x] Blockstack.com – [#517: Design image for timeline on blockstack.com](https://github.com/blockstack/designs/issues/517)
- [x] [#534: Review new PDF designs](https://github.com/blockstack/designs/issues/534) by @MechanicalHuman
- [x] [#539: Gather team images for blockstack.com](https://github.com/blockstack/designs/issues/539)
- [x] [#540: Gather investor logos](https://github.com/blockstack/designs/issues/540)
- [x] [#532: Blog post image for release](https://github.com/blockstack/designs/issues/532)
- [x] [#537: Keynote/PDF design plan](https://github.com/blockstack/designs/issues/537)
- [x] [#456: Build HTML/CSS button for blog post](https://github.com/blockstack/blockstack.org/issues/456)

_**ahead**_:
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Add Token Banner back to website
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#530: design standup – Wed, Oct 30, 2017](https://github.com/blockstack/designs/issues/530)

**Comment by estermer** [comment]
**Yesterday:** Nothing
**Today:** waiting for input on bounties ticket from @pstan26 then going to review how to get going on it.
