### ISSUE TITLE
design standup – Fri, Oct 27, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#546]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Coinlist-Blockstack.com-FyFo57w7gYbu5DcBh5PsJ)

----

_**yesterday**_:
- [x] Coinlist – Coinlist/blockstack coordination
- [x] Blockstack.com – coordination
- [x] Worked on v2 [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- Went home early to rest. All nighter the night before.

_**today**_:
- [x] Coinlist – Quick 10 min meeting with Paul and Brian to discuss deliverables and where we're at.
    - Created new Coinlist/Blockstack Home page wish list - 
- [x] [#12: Berlin Conference video](https://github.com/blockstackinc/signature-fund/issues/12) review
- [x] Frontend product meeting w/ @shea256 @larrysalibra @yknl @kantai 
- [x] Blockstack.com – coordination for new requirements for Wednesday
- [x] [Setup Blockstack Token Survey](https://github.com/blockstackinc/tokensale/issues/154)
- [x] [#547: Updated version of the token whitepaper cover](https://github.com/blockstack/designs/issues/547)
- [x] Full UX/UI browser review w/ @yknl - [Browser UI/UX Review](https://paper.dropbox.com/doc/Browser-UIUX-Oct-27-6S7A6BjsQNFBtOQ0DUCge)
- [x] Blockstack.org – [#458: Reinstate the banner for the token sale and link to blockstack.com](https://github.com/blockstack/blockstack.org/issues/458)
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] Coinlist – Coinlist/blockstack coordination
- [ ] Blockstack.org – [#455: Wrap anchor tag around div/button so button is clickable on blog post](https://github.com/blockstack/blockstack.org/issues/455)
- [ ] Help out Steven with some naming

_**ahead**_:
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#546: design standup – Fri, Oct 27, 2017](https://github.com/blockstack/designs/issues/546)
