### ISSUE TITLE
design standup – Mon, Oct 30, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#552]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Coinlist-Blockstack.com-FyFo57w7gYbu5DcBh5PsJ)
- [Monday Checklist](https://github.com/blockstackinc/tokensale/issues/153)
- [Wednesday Checklist](https://github.com/blockstackinc/tokensale/issues/155)

----

_**friday, saturday, sunday**_:
- [x] Coinlist – Quick 10 min meeting with Paul and Brian to discuss deliverables and where we're at.
    - Created new Coinlist/Blockstack Home page wish list - 
- [x] [#12: Berlin Conference video](https://github.com/blockstackinc/signature-fund/issues/12) review
- [x] Frontend product meeting w/ @shea256 @larrysalibra @yknl @kantai 
- [x] Blockstack.com – coordination for new requirements for Wednesday
- [x] [Setup Blockstack Token Survey](https://github.com/blockstackinc/tokensale/issues/154)
- [x] [#547: Updated version of the token whitepaper cover](https://github.com/blockstack/designs/issues/547)
- [x] Full UX/UI browser review w/ @yknl - [Browser UI/UX Review](https://paper.dropbox.com/doc/Browser-UIUX-Oct-27-6S7A6BjsQNFBtOQ0DUCge)
- [x] Blockstack.org – [#458: Reinstate the banner for the token sale and link to blockstack.com](https://github.com/blockstack/blockstack.org/issues/458)
- [x] Coinlist – Coinlist/blockstack coordination

_**today**_:
- [x] Blockstack.com – Project coordination
- [x] Blockstack.com – [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)
- [ ] ~~Blockstack.com – [#202: Design non-accredited flow select register view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/202)~~
- [ ] ~~Blockstack.com – [#203: Design non-accredited flow select income view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/203)~~
- [x] Blockstack.com – [#204: Design non-accredited flow instructions view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/204)
- [x] Browser – Frontend meeting with @shea256, @larrysalibra, @yknl 
- [x] Blockstack.com – Round 2 [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)
- [x] Blockstack.com – [#205: Enter registration info](https://github.com/blockstackinc/blockstack-dot-com/issues/205)
- [x] [#553: Redesign suggestion for Vertua app](https://github.com/blockstack/designs/issues/553)
- [x] Blockstack.com – [#195: Confirmation Page](https://github.com/blockstackinc/blockstack-dot-com/issues/195)
- [x] Blockstack.com – Round 3 [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)
- [ ] Blockstack.com – [#198: Error conditions when not enough social accounts](https://github.com/blockstackinc/blockstack-dot-com/issues/198)
- [ ] Blockstack.com – [#206: Screen for NY Residents](https://github.com/blockstackinc/blockstack-dot-com/issues/206)
- [ ] Blockstack.com – [#196: Email confirmation](https://github.com/blockstackinc/blockstack-dot-com/issues/196)
- [ ] [#370: Blog image](https://github.com/blockstack/blockstack/issues/370)
- [ ] Browser – [#983: Update primary navbar and be sticky](https://github.com/blockstack/blockstack-browser/issues/983)
- [ ] Browser – [#984: Update secondary navbar to use buttons only](https://github.com/blockstack/blockstack-browser/issues/984)
- [ ] Browser – [#985: Update buttons / hover states](https://github.com/blockstack/blockstack-browser/issues/985)

_**ahead**_:
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] Blockstack.org – [#455: Wrap anchor tag around div/button so button is clickable on blog post](https://github.com/blockstack/blockstack.org/issues/455)
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Help out Steven with some naming
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#552: design standup – Mon, Oct 30, 2017](https://github.com/blockstack/designs/issues/552)
