### ISSUE TITLE
design standup – Tue, Oct 31, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#554]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [›› Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/3)
- [Wednesday Checklist](https://github.com/blockstackinc/tokensale/issues/155)
- https://github.com/blockstackinc/blockstack-dot-com/issues/222

----

_**yesterday**_:
- [x] Blockstack.com – Project coordination
- [x] Blockstack.com – [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)
- [ ] ~~Blockstack.com – [#202: Design non-accredited flow select register view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/202)~~
- [ ] ~~Blockstack.com – [#203: Design non-accredited flow select income view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/203)~~
- [x] Blockstack.com – [#204: Design non-accredited flow instructions view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/204)
- [x] Browser – Frontend meeting with @shea256, @larrysalibra, @yknl 
- [x] Blockstack.com – Round 2 [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)
- [x] Blockstack.com – [#205: Enter registration info](https://github.com/blockstackinc/blockstack-dot-com/issues/205)
- [x] [#553: Redesign suggestion for Vertua app](https://github.com/blockstack/designs/issues/553)
- [x] Blockstack.com – [#195: Confirmation Page](https://github.com/blockstackinc/blockstack-dot-com/issues/195)
- [x] Blockstack.com – Round 3 [#201: Design new home registration view blockstack.com design](https://github.com/blockstackinc/blockstack-dot-com/issues/201)

_**today**_:
- [x] Browser – [#983: Update primary navbar and be sticky](https://github.com/blockstack/blockstack-browser/issues/983)
- [x] Browser – [#788: review all button states](https://github.com/blockstack/blockstack-browser/issues/788)
- [x] [#370: Blog image](https://github.com/blockstack/blockstack/issues/370)
- [x] Blockstack.com – [#195: Confirmation Page Design](https://github.com/blockstackinc/blockstack-dot-com/issues/195)
- [x] Blockstack.com – [#196: Email confirmation](https://github.com/blockstackinc/blockstack-dot-com/issues/196)
- [x] Blockstack.com – [#220: Blockstack authentication icons](https://github.com/blockstackinc/blockstack-dot-com/issues/220)
- [x] Blockstack.com – [#198: Error conditions when not enough social accounts](https://github.com/blockstackinc/blockstack-dot-com/issues/198)
- [ ] ›› Blockstack.com – [#206: Screen for NY Residents](https://github.com/blockstackinc/blockstack-dot-com/issues/206)
- [ ] Browser – [#984: Update secondary navbar to use buttons only](https://github.com/blockstack/blockstack-browser/issues/984)

_**ahead**_:
- [ ] Browser – [#1002: The global full width container class has max-width definition](https://github.com/blockstack/blockstack-browser/issues/1002)
- [ ] Browser – [#555: Design new global support button for browser](https://github.com/blockstack/designs/issues/555)
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] Blockstack.org – [#455: Wrap anchor tag around div/button so button is clickable on blog post](https://github.com/blockstack/blockstack.org/issues/455)
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Help out Steven with some naming
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#554: design standup – Tue, Oct 31, 2017](https://github.com/blockstack/designs/issues/554)
