### ISSUE TITLE
design standup – Fri, Nov 3, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#560]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [›› Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/3)

----

_**yesterday**_:
- [x] Front end meeting w/ @larrysalibra @yknl - [Token Sale Registration Problems - Nov 2, 2017](https://paper.dropbox.com/doc/Token-Sale-Registration-Problems-Nov-2-2017-zTiYwuwVpYXOSJjpyICtR)
- [x] Browser – [#984: Update secondary navbar to use buttons only](https://github.com/blockstack/blockstack-browser/issues/984)
- [x] Browser – [#1024: Make add username a button from link on profile](https://github.com/blockstack/blockstack-browser/issues/1024)
- [x] Browser – [#1025: Update navbar links and icon sizes, and increase navbar height](https://github.com/blockstack/blockstack-browser/issues/1025)
- [x] Blockstack.com – Project coordination
- [x] All hands meeting/conference call
- [x] Blockstack.com – Review all Ready for Acceptance items
- [x] Blockstack.com – [#559: $3,000+ update to hero on blockstack.com](https://github.com/blockstack/designs/issues/559)

_**today**_:
- [x] Blockstack.com – Review all Ready for Acceptance items
- [x] Browser – Quick review of latest changes
- [x] Browser – Write up issues with [#1032: Trust Level UI improvement](https://github.com/blockstack/blockstack-browser/issues/1032)
- [x] Blockstack.com – [#335: Add the video back in](https://github.com/blockstackinc/blockstack-dot-com/issues/335)
- [x] Blockstack.com – [#336: Update sale registration page](https://github.com/blockstackinc/blockstack-dot-com/issues/336)
- [x] Blockstack.com – [#561: New placeholder image for blockstack video](https://github.com/blockstack/designs/issues/561)
- [x] Blockstack.com – Round 1 [#338: Add video, countdown timer, and indication of CoinList timeline above the fold](https://github.com/blockstackinc/blockstack-dot-com/issues/338)
- [x] Blockstack.com – Round 2 [#338: Add video, countdown timer, and indication of CoinList timeline above the fold](https://github.com/blockstackinc/blockstack-dot-com/issues/338)
- [x] Blockstack.com – Round 3 & UI build w/ @tracedwax [#338: Add video, countdown timer, and indication of CoinList timeline above the fold](https://github.com/blockstackinc/blockstack-dot-com/issues/338)
- [ ] Browser – New item
- [ ] Browser – [#904: Resolve tooltip UI](https://github.com/blockstack/blockstack-browser/issues/904)
- [ ] Browser – [#906: Tool tips should appear over mouse](https://github.com/blockstack/blockstack-browser/issues/906)
- [ ] Blockstack.com – [#316: Change 500 error message?](https://github.com/blockstackinc/blockstack-dot-com/issues/316)
- [ ] Blockstack.com – Project coordination

_**ahead**_:
- [ ] Browser – [#1002: The global full width container class has max-width definition](https://github.com/blockstack/blockstack-browser/issues/1002)
- [ ] Browser – [#555: Design new global support button for browser](https://github.com/blockstack/designs/issues/555)
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Help out Steven with some naming
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#560: design standup – Fri, Nov 3, 2017](https://github.com/blockstack/designs/issues/560)
