### ISSUE TITLE
design standup – Tue, Nov 7, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#566]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_:
- [x] Blockstack.com – Iteration 1 [#563: Create new founders video placeholder image](https://github.com/blockstack/designs/issues/563)
- [x] Blockstack.com – Iteration 2 [#563: Create new founders video placeholder image](https://github.com/blockstack/designs/issues/563)
- [x] Blockstack.org – [#462: Update text editor identity svg img](https://github.com/blockstack/blockstack.org/issues/462)
- [x] Blockstack.com – Review all Ready for Acceptance items

_**today**_:
- [x] Browser – [#1041: Produce new icons for home screen](https://github.com/blockstack/blockstack-browser/issues/1041)
- [ ] Browser – [#1042: Add 7 new apps to Home Screen](https://github.com/blockstack/blockstack-browser/issues/1042)
    - [ ] Browser – [#934: Add "Souq" to app store](https://github.com/blockstack/blockstack-browser/issues/934)
- [ ] Onename.com – [#80: Resolve html/css/scss breakages in build](https://github.com/blockstackinc/onename-site/issues/80)
- [ ] Browser – [#1033: Build new token sale disclaimer](https://github.com/blockstack/blockstack-browser/issues/1033)
- [ ] Blockstack.org – [#459: Add countdown timer to banner](https://github.com/blockstack/blockstack.org/issues/459)
- [ ] Token – [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] Token – [#565: Blockstack distribution PDF doc v2](https://github.com/blockstack/designs/issues/565)
- [ ] Blockstack.com – [#209: Blockstack.com/legal - PDF improvements](https://github.com/blockstackinc/tokensale/issues/209)
- [ ] Browser – New item
- [ ] Browser – [#904: Resolve tooltip UI](https://github.com/blockstack/blockstack-browser/issues/904)
- [ ] Browser – [#906: Tool tips should appear over mouse](https://github.com/blockstack/blockstack-browser/issues/906)
- [ ] Blockstack.com – [#316: Change 500 error message?](https://github.com/blockstackinc/blockstack-dot-com/issues/316)
- [ ] Blockstack.com – Project coordination

_**ahead**_:
- [ ] Browser – [#896: Add Studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#1002: The global full width container class has max-width definition](https://github.com/blockstack/blockstack-browser/issues/1002)
- [ ] Browser – [#555: Design new global support button for browser](https://github.com/blockstack/designs/issues/555)
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Help out Steven with some naming
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#566: design standup – Tue, Nov 7, 2017](https://github.com/blockstack/designs/issues/566)
