### ISSUE TITLE
design standup – Mon, Nov 13, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#577]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**friday, saturday, sunday**_:
- [x] Outreach
- [x] Blockstack.com – Mobile image of [#572: New market cap chart for blockstack.com](https://github.com/blockstack/designs/issues/572)
- [x] Blockstack.com – [#391: Adjustments to Market Cap section](https://github.com/blockstackinc/blockstack-dot-com/issues/391)
- [x] Browser – [#1045: Review transfer Blockstack ID from Onename to Browser process](https://github.com/blockstack/blockstack-browser/issues/1045)
- [x] Blockstack.com – Project coordination
- [x] Browser – Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [x] Token – Worked on Write up full review of registration process https://github.com/blockstackinc/tokensale/issues/221

_**today**_:
- [x] Browser – Adding three new apps to the app store https://github.com/blockstack/blockstack-browser/issues/1065
- [x] Blockstack.com – Cleanup SCSS throughout https://github.com/blockstackinc/blockstack-dot-com/issues/406
- [x] Weekly meeting
- [x] Browser –  Updated "Coinstack A" to "Coinstack" and removing the Blockportfolio app https://github.com/blockstack/blockstack-browser/issues/1065
- [x] Blockstack.com – Create New changes list https://github.com/blockstackinc/blockstack-dot-com/issues/412
- [x] Blockstack.com – Call with @tracedwax
- [x] Blockstack.com – Design navbar for Blockstack.com https://github.com/blockstack/designs/issues/574
- [x] Blockstack.com – Create new tab navbar below hero https://github.com/blockstackinc/blockstack-dot-com/issues/411
- [x] Blockstack.com – Worked on Changes to /legal page https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [x] Blockstack.com – Project coordination
- [x] Apps – Did a quick review of the Coins app with Chase
- [ ] Coinlist – Request updates from Paul
- [ ] Blockstack.com – Have @shea256 provide creds for Add Sift Science or Onfido https://github.com/blockstackinc/blockstack-dot-com/issues/226
- [ ] Browser – Drop shadow and corners on home screen apps needs adjusting https://github.com/blockstack/blockstack-browser/issues/1067
- [ ] Blockstack.com – Design navbar links into footer of Blockstack.com https://github.com/blockstack/designs/issues/575
- [ ] Browser – Finish Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [ ] Token – Finish Write up full review of registration process https://github.com/blockstackinc/tokensale/issues/221
- [ ] Onename.com – [#80: Resolve html/css/scss breakages in build](https://github.com/blockstackinc/onename-site/issues/80)
- [ ] Token – [#545: Blockstack overview PDF doc v2](https://github.com/blockstack/designs/issues/545)
- [ ] Token – [#565: Blockstack distribution PDF doc v2](https://github.com/blockstack/designs/issues/565)
- [ ] Blockstack.com – [#209: Blockstack.com/legal - PDF improvements](https://github.com/blockstackinc/tokensale/issues/209)

_**ahead**_:
- [ ] Browser – [#904: Resolve tooltip UI](https://github.com/blockstack/blockstack-browser/issues/904)
- [ ] Browser – [#906: Tool tips should appear over mouse](https://github.com/blockstack/blockstack-browser/issues/906)
- [ ] Browser – [#1002: The global full width container class has max-width definition](https://github.com/blockstack/blockstack-browser/issues/1002)
- [ ] Browser – [#555: Design new global support button for browser](https://github.com/blockstack/designs/issues/555)
- [ ] Blockstack Overview Doc – [#542: Build creative brief for keynote/PDF Blockstack overview doc](https://github.com/blockstack/designs/issues/542)
- [ ] [#535: New Stacks symbol](https://github.com/blockstack/designs/issues/535)
- [ ] [#536: Team hover descriptions on blockstack.com](https://github.com/blockstack/designs/issues/536)
- [ ] Help out Steven with some naming
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#577: design standup – Mon, Nov 13, 2017](https://github.com/blockstack/designs/issues/577)
