### ISSUE TITLE
design standup – Mon, Nov 20, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#581]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**thursday, friday, saturday, sunday**_:
- [x] Blockstack.com – Worked with @larrysalibra on some issues he was having on the site
- [x] Blockstack.com – Design new hero / home sections for 12noon Sale Starts https://github.com/blockstackinc/blockstack-dot-com/issues/468
- [x] Blockstack.com – Update Market Cap Bar Chart to $0.12 https://github.com/blockstackinc/blockstack-dot-com/issues/475
- [x] Blockstack.com – Design new hero / home sections for 6pm Initial Sale Stop https://github.com/blockstackinc/blockstack-dot-com/issues/480
- [x] Had some items to deal with for 83(b) election
- [x] Blockstack.com – Project coordination
- [x] Blockstack.com – Create new tab navbar below hero https://github.com/blockstackinc/blockstack-dot-com/issues/411

_**today**_:
- [x] Blockstack.com – Cleanup
- [x] Weekly meeting
- [x] Browser – GitHub Sprint 0.20 & 0.21 cleanup
- [x] Blockstack.com – Review team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [x] Blockstack.com – Call with @tracedwax to go over Sprint 6
- [x] Blockstack.com – Markup and copy and styling for team members, https://github.com/blockstackinc/blockstack-dot-com/issues/432
- [x] Blockstack.com – Update team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [ ] Blockstack.com – The changes you wanted to make to the legal page, https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [ ] Browser – Add Coinfolio to home screen

_**ahead**_:

Link to today's open source design contributor standup:
- [#581: design standup – Mon, Nov 20, 2017](https://github.com/blockstack/designs/issues/581)
