### ISSUE TITLE
design standup – Tue, Nov 21, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#582]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**yesterday**_:
- [x] Blockstack.com – Cleanup
- [x] Weekly meeting
- [x] Browser – GitHub Sprint 0.20 & 0.21 cleanup
- [x] Blockstack.com – Review team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [x] Blockstack.com – Call with @tracedwax to go over Sprint 6
- [x] Blockstack.com – Markup and copy and styling for team members, https://github.com/blockstackinc/blockstack-dot-com/issues/432
- [x] Blockstack.com – Update team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [x] Blockstack.com – Project coordination

_**today**_:
- [x] Browser – Frontend meeting w/ @larrysalibra @yknl @shea256 
- [x] Browser – Add Coinfolio to home screen https://github.com/blockstack/blockstack-browser/issues/1089
- [x] Personal meetings (x2)
- [x] Browser – Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [x] Blockstack.com – The changes you wanted to make to the legal page, https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [ ] Blockstack.com – Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512

Link to today's open source design contributor standup:
- [#582: design standup – Tue, Nov 21, 2017](https://github.com/blockstack/designs/issues/582)
