### ISSUE TITLE
design standup – Wed, Nov 22, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#584]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**tuesday**_:
- [x] Browser – Frontend meeting w/ @larrysalibra @yknl @shea256 
- [x] Browser – Add Coinfolio to home screen https://github.com/blockstack/blockstack-browser/issues/1089
- [x] Personal meetings (x2)
- [x] Browser – Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [x] Blockstack.com – The changes you wanted to make to the legal page, https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [x] Blockstack.com – Project coordination

_**today**_:
- [x] Personal errands
- [ ] Blockstack.com – Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512
- [ ] Token – Live design token voucher email https://github.com/blockstackinc/blockstack-dot-com/issues/533
- [ ] Token – Design token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534

Link to today's open source design contributor standup:
- [#583: design standup – Wed, Nov 22, 2017](https://github.com/blockstack/designs/issues/583)
