### ISSUE TITLE
design standup – Mon, Nov 27, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#585]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)
- https://paper.dropbox.com/doc/Design-meeting-G9pfeDKfuaE0T3iQYmZoj

----

_**wednesday & long weekend**_:
- [x] Personal errands
- [x] Browser – Went through all comments on issues.
- [x] Browser – Designed progress bar button for No visual indicator on restore from backup phrase https://github.com/blockstack/blockstack-browser/issues/1082
- [x] Browser – Update Arenaplay logo in next release https://github.com/blockstack/designs/issues/583
- [x] Blockstack.org – Link to mac browser on install page not current https://github.com/blockstack/blockstack.org/issues/465

_**today**_:
- [x] Blockstack.com – Finalize Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512
- [x] Weekly meeting
- [x] Token – Design token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534
- [x] Discussed chat app bounty and funding w/ @pstan26 https://github.com/blockstack/designs/issues/586
- [ ] Token – Live design token voucher email https://github.com/blockstackinc/blockstack-dot-com/issues/533
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#585: design standup – Mon, Nov 27, 2017](https://github.com/blockstack/designs/issues/585)
