### ISSUE TITLE
design standup – Tue, Nov 28, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#589]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)
- https://paper.dropbox.com/doc/Design-meeting-G9pfeDKfuaE0T3iQYmZoj

----

_**yesterday**_:
- [x] Blockstack.com – Finalize Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512
- [x] Weekly meeting
- [x] Token – Design token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534
- [x] Discussed chat app bounty and funding w/ @pstan26 https://github.com/blockstack/designs/issues/586

_**today**_:
- [x] Blockstack.com – Project coordination
- [x] Blockstack.com – Worked on new messaging layout for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512
- [x] Token – Applied new content and adjusted layout of token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534
- [x] Had meeting and discussed chat app bounty and funding w/ @pstan26 https://github.com/blockstack/designs/issues/586
- [x] Token – Investor coordination
- [x] Researched the history of the web browser https://github.com/blockstack/designs/issues/588
- [x] Researched InVision Design System Manager & InVision Studio https://github.com/blockstack/designs/issues/587
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Token – Design token voucher email https://github.com/blockstackinc/blockstack-dot-com/issues/533
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#588: design standup – Tue, Nov 28, 2017](https://github.com/blockstack/designs/issues/588)
