### ISSUE TITLE
design standup – Thu, Dec 7, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#595]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)
- https://paper.dropbox.com/doc/Design-meeting-G9pfeDKfuaE0T3iQYmZoj

----

_**friday, saturday, sunday**_:
- [x] Blockstack.com – Project coordination
- [x] Token – Adjustments to token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534
- [x] Blockstack.com – Live design token redemption page https://github.com/blockstackinc/blockstack-dot-com/issues/544
- [x] Blockstack.com – Design new condensed email header image for voucher email https://github.com/blockstackinc/blockstack-dot-com/issues/545
- [x] Blockstack.com – Update to subtitle on home page https://github.com/blockstackinc/blockstack-dot-com/commit/5d5893f7430a124ebe3a564edbc23d208bd011ed
- [x] Blockstack.com – Fixed typo on home page https://github.com/blockstackinc/blockstack-dot-com/issues/544

_**monday, tuesday, wednesday**_:
- [x] Blockstack retreat
- [x] Blog – Design banner image for token distribution press release https://github.com/blockstack/designs/issues/594
- [x] Blockstack.org – Reviewed and approved pull request https://github.com/blockstack/blockstack.org/pull/471 Update Careers page photo and spacing
- [x] Blockstack.org – Reviewed and approved pull request https://github.com/blockstack/blockstack.org/pull/469 Fix side menu scrolling in docs and faq

_**today**_:
- [x] Auth – Tracked down and provided @pstan26 with latest Blockstack Auth button set 
- [x] Hiring meeting
- [x] Auth – Worked on Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#595: design standup – Thu, Dec 7, 2017](https://github.com/blockstack/designs/issues/595)
