### ISSUE TITLE
design standup – Fri, Dec 8, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#598]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)
- https://paper.dropbox.com/doc/Design-meeting-G9pfeDKfuaE0T3iQYmZoj

----

_**thursday**_:
- [x] Auth – Tracked down and provided @pstan26 with latest Blockstack Auth button set 
- [x] Hiring meeting
- [x] Auth – Worked on Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596

_**today**_:
- [x] Design discovery
- [x] Hiring meeting
- [x] Front-end meeting – https://paper.dropbox.com/doc/Front-end-Meeting-PdfN8PjlY0nn8gNFz56vJ
- [x] Research on devlink app design w/ @pstan26 
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#598: design standup – Fri, Dec 8, 2017](https://github.com/blockstack/designs/issues/598)
