### ISSUE TITLE
design standup – Sat, Dec 9, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#599]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**friday**_:
- [x] Design discovery
- [x] Hiring meeting
- [x] Front-end meeting – https://paper.dropbox.com/doc/Front-end-Meeting-PdfN8PjlY0nn8gNFz56vJ
- [x] Research on devlink app design w/ @pstan26 

_**today**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549

_**ahead**_:
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#599: design standup – Sat, Dec 9, 2017](https://github.com/blockstack/designs/issues/599)
