### ISSUE TITLE
design standup – Mon, Dec 18, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#602]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**sunday**_:
- [x] Review of all GitHub issues
- [x] Catch up on email and Slack

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [x] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Signature Fund – Create Image for Messaging Plugin Bounty https://github.com/blockstackinc/design/issues/11
- [ ] Signature Fund – Create Image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12

_**ahead**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#602: design standup – Mon, Dec 18, 2017](https://github.com/blockstack/designs/issues/602)
