### ISSUE TITLE
design standup – Wed, Dec 20, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#604]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**monday**_:
- [x] Browser – Add new Coinstack app icon to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [x] Signature Fund – Design Eventbrite image for Encrypted & Decentralized P2P Messaging Bounty https://github.com/blockstackinc/design/issues/11
- [x] Signature Fund – Design Eventbrite image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12
- [x] Signature Fund – Design blog post image for Decentralize Communication Bounty https://github.com/blockstackinc/design/issues/13

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [x] Signature Fund – Make changes to blog post image for Bounty to Decentralize Communication https://github.com/blockstackinc/design/issues/13
- [x] Signature Fund – Make requested change to Eventbrite image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12

_**ahead**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#604: design standup – Wed, Dec 20, 2017](https://github.com/blockstack/designs/issues/604)
