### ISSUE TITLE
design standup – Fri, Dec 22, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#605]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**tuesday, wednesday, thursday**_:
- [x] Signature Fund – Make changes to blog post image for Bounty to Decentralize Communication https://github.com/blockstackinc/design/issues/13
- [x] Signature Fund – Make requested change to Eventbrite image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12
- [x] Browser – Discussion around Isotach Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139

_**ahead**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#605: design standup – Fri, Dec 22, 2017](https://github.com/blockstack/designs/issues/605)
