### ISSUE TITLE
design standup – Wed, Jan 3, 2018

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#606]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**this week**_:
- [x] Create new sprint board
- [x] Catch up on GitHub & email
- [x] Weekly team meeting
- [ ] Review Brand
- [ ] Review Browser
- [ ] Review Brand Guide
- [ ] Review Design System
- [ ] Meet with Ken to discuss design goals
- [ ] Create a Design Roadmap including quarterly, bi-annual & annual goals separated by product
- [ ] Meet with Ryan and Ken about final design goals
- [ ] Write list of what a design team can do and the roles that they would play

_**ahead**_:
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#606: design standup – Wed, Jan 3, 2018](https://github.com/blockstack/designs/issues/606)
