### ISSUE TITLE
brand-v3.0.0 publish list

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#74]
[brand-v3.0.0 Milestone](https://github.com/blockstack/designs/milestone/1)

#### Tasks
- [x] https://github.com/blockstack/designs/issues/8: new version illustration for releases
- [x] https://github.com/blockstack/designs/issues/89: blockstack gradient color design
- [x] https://github.com/blockstack/designs/issues/53: Design new Blockstack bug and logo
- [x] https://github.com/blockstack/designs/issues/63: Create sketch color palette assets
- [x] https://github.com/blockstack/designs/issues/54: Create new blockstack purple logo
- [x] https://github.com/blockstack/designs/issues/32: Design new blockstack atlas grid illustration / brand graphics
- [x] https://github.com/blockstack/designs/issues/31: Create new blockstack blog logo
- [x] https://github.com/blockstack/designs/issues/75: Create twitter image template
- [x] https://github.com/blockstack/designs/issues/60: Create branding for Microsoft Marketplace
- [x] https://github.com/blockstack/designs/issues/73: define new label color for publish list
- [x] https://github.com/blockstack/designs/issues/72: define new blockstack highlight color(s)
- [x] https://github.com/blockstack/designs/issues/86: Icon set
- [x] https://github.com/blockstack/designs/issues/84: Core design decisions and discoveries
- [x] https://github.com/blockstack/designs/issues/98: blockstack logo and bug production (v1)
- [x] https://github.com/blockstack/designs/issues/99: new blockstack favicon
- [x] https://github.com/blockstack/designs/issues/28: update twitter branding
- [x] https://github.com/blockstack/designs/issues/5: invision brand board v1
- [x] https://github.com/blockstack/designs/issues/110: Create all square blockstack icons
- [x] https://github.com/blockstack/designs/issues/3: update blockstack youtube channel branding
- [x] https://github.com/blockstack/designs/issues/65: Defined ALL new blockstack colors and color sets
- [x] https://github.com/blockstack/designs/issues/118: design secondary product logo branding
- [x] https://github.com/blockstack/designs/issues/113: create rounded blockstack icons
- [x] https://github.com/blockstack/designs/issues/112: update filenames of all logos from bsk to blockstack
- [x] https://github.com/blockstack/designs/issues/1: Updated blockstack bug colors
- [x] https://github.com/blockstack/designs/issues/132: remove brand footer from twitter image
- [x] https://github.com/blockstack/designs/issues/138: transfer blockstack newsletter template to blockstack mailchimp
- [x] https://github.com/blockstack/designs/issues/124: decentralize the web challenge eventbrite banner image
- [x] https://github.com/blockstack/designs/issues/140: blockstack newsletter update logo and remove reddit social link
- [x] https://github.com/blockstack/designs/issues/147: remove medium link for forum on blockstack newsletter
- [x] https://github.com/blockstack/designs/issues/149: adjust html in header to allow for constant flow of items by editor
- [x] https://github.com/blockstack/designs/issues/145: update blockstack meetup banner design
- [x] https://github.com/blockstack/designs/issues/160: new meetup icon for blockstack newsletter
- [x] https://github.com/blockstack/designs/issues/152: blog banner image for blockstack auth blog post
- [x] https://github.com/blockstack/designs/issues/119: blockstack explorer blog post imagery
- [x] https://github.com/blockstack/designs/issues/150: Create 2:4(?) ratio twitter image for #DecentralizeTheWeb tweets
- [x] https://github.com/blockstack/designs/issues/161: quick design of a cryptocracy agora logo
- [x] https://github.com/blockstack/designs/issues/173: coindesk construct conference presentation deck (keynote)
- [x] https://github.com/blockstack/designs/issues/135: CLI command video tutorial title slide template
- [x] https://github.com/blockstack/designs/issues/183: inverse color of ovals, rectangles and lines atlas illustration
- [x] https://github.com/blockstack/designs/issues/176: Twitter image for CLI Tutorial video announcement

#### Bugs
- [x] https://github.com/blockstack/designs/issues/156: bug: blockstack newsletter resolve body copy font issue
- [x] https://github.com/blockstack/designs/issues/155: bug: blockstack newsletter resolve website mentions with tld

**Comment by guylepage3** [comment]
Complete https://github.com/blockstack/designs/issues/53: Design new Blockstack bug and logo

**Comment by guylepage3** [comment]
Complete https://github.com/blockstack/designs/issues/86: Icon set

**Comment by guylepage3** [comment]
Complete. https://github.com/blockstack/designs/issues/84: Core design decisions and discoveries

**Comment by guylepage3** [comment]
Complete. https://github.com/blockstack/designs/issues/98: blockstack logo and bug production (v1)

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/designs/issues/99: new blockstack favicon

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/designs/issues/28: update twitter branding

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/designs/issues/5: invision brand board v1

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/designs/issues/110: Create all blockstack icons for metadata and other use cases

**Comment by guylepage3** [comment]
complete. https://github.com/blockstack/designs/issues/3: update blockstack youtube channel branding

**Comment by guylepage3** [comment]
complete. #118: design secondary product logo branding

**Comment by guylepage3** [comment]
complete. #113: create rounded blockstack icons

**Comment by guylepage3** [comment]
complete. #112: update filenames of all logos from bsk to blockstack
