### ISSUE TITLE
icon set design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#86]
**Task**
Design and produce a Blockstack icons.

**Design requirements**
- Minimalistic
- Simple
- Clean
- Modern
- Neutral.

**Icons**
- [x] Hello Blockstack!
- [x] Identity
- [x] blockstack.org
- [x] Settings

**Comment by guylepage3** [comment]
Blockstack icons should follow the standard sizes below that used by both the Apple App Store and Google Play Store

```
16x16
19x19
24x24
29x29
32x32
36x36
38x38
40x40
48x48
58x58
60x60
64x64
70x70
72x72
76x76
80x80
87x87
96x96
114x114
120x120
128x128
140x140
150x150
152x152
180x180
192x192
256x256
310x310
512x512
1024x1024
```

**Comment by guylepage3** [comment]
Icon concepts
- [ ] large icons set on a rectangle w/rounded corners
- [ ] small icon to the left with type to the right set on a rectangle w/rounded corners
- [ ] 60º angled grate covered icon
- [ ] bubble style icons
- [ ] contour style icons
- [ ] layered style icons
- [ ] ultra flat icons
- [ ] mosaic style icons
- [ ] simple rastor image style icons
- [ ] polygon grid style icons
- [ ] contour with gradient style icons

**Comment by guylepage3** [comment]
- [ ] button style background with inset icon
- [ ] broken glass style icons
- [ ] dot style icons
- [ ] 3d style icons with 1/4 broken... symbolizing decentralization
- [ ] button background that contains a line grid that all icons must utilize
- [ ] neutral gray gradient colors

**Comment by guylepage3** [comment]
created an icon inspiration board on pinterest.com
https://www.pinterest.com/guylepage3/icons/

**Comment by guylepage3** [comment]
More design rules;
- icons should stay away from ethereum branding
- icons should reflect blockstack in a unique way that others can adapt the brand for their own purposes

**Comment by guylepage3** [comment]
![app-identity](https://cloud.githubusercontent.com/assets/1711854/21613614/f7663b72-d1a3-11e6-83e8-8ed36b6e47ef.png)

**Comment by guylepage3** [comment]
![app-settings](https://cloud.githubusercontent.com/assets/1711854/21614068/082b9d1a-d1a6-11e6-9d33-2ff47557f759.png)

**Comment by guylepage3** [comment]
![app-blockstackorg](https://cloud.githubusercontent.com/assets/1711854/21614121/35de6c10-d1a6-11e6-9efc-1bd11be57bd1.png)

**Comment by guylepage3** [comment]
![app-hello-blockstack](https://cloud.githubusercontent.com/assets/1711854/21614244/aceae2c0-d1a6-11e6-80e0-0394a49917b8.png)

**Comment by larrysalibra** [comment]
I like them!  Looking good @guylepage3 !

**Comment by guylepage3** [comment]
Closing this issue

**Comment by shea256** [comment]
Very nice @guylepage3! Can we integrate them into the browser now?

**Comment by guylepage3** [comment]
Yes please.. The designs should have been in this repo. i was wondering why we were using the old ones. My bad. 😄

**Comment by guylepage3** [comment]
![app-blockstackorg](https://cloud.githubusercontent.com/assets/1711854/22127265/42324728-de69-11e6-9658-edf4e35a494d.png)
![app-hello-blockstack](https://cloud.githubusercontent.com/assets/1711854/22127266/4236751e-de69-11e6-9daf-dae80f6f0dc9.png)
![app-identity](https://cloud.githubusercontent.com/assets/1711854/22127267/42395b3a-de69-11e6-8239-28f875b82b33.png)
![app-settings](https://cloud.githubusercontent.com/assets/1711854/22127268/423dcf1c-de69-11e6-97b2-413a3dfa2616.png)

**Comment by guylepage3** [comment]
@shea256 @larrysalibra I've just updated the apps above. they had a shadow around the edge before. Please use these new ones. Thanks.

**Comment by shea256** [comment]
ok cool
