### ISSUE TITLE
brand-v2.7.0 publish list

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#88]
### Highlights

- [ ] https://github.com/blockstack/designs/issues/87: Icon set standards guide
- [ ] https://github.com/blockstack/designs/issues/68: Blockstack gradient color design
- [ ] https://github.com/blockstack/designs/issues/10: Blockstack social and footer template protocol
- [ ] https://github.com/blockstack/designs/issues/9: Design and build new Blockstack Blog Medium layout
- [ ] https://github.com/blockstack/designs/issues/52: Add to public invision board
- [ ] https://github.com/blockstack/designs/issues/11: Sketch asset files
- [ ] https://github.com/blockstack/designs/issues/41: Create shared asset library in sketch
