### ISSUE TITLE
update of all blockstack social sites with new brand/logo

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#97]
Update of all blockstack social sites with new brand, colors and logo

**Instances**
- [x] Facebook - [facebook.com/blockstack](https://www.facebook.com/blockstack)
- [x] Twitter - [twitter.com/blockstackorg](https://twitter.com/blockstackorg)
- [x] LinkedIn - https://www.linkedin.com/company-beta/10624288/
- [x] YouTube - [YouTube](https://www.youtube.com/channel/UCiyMoKVWkVdC_sC0CqrxCoQ)
  - [x] Logo
  - [x] Banner
  - [x] Watermark (Assigned to Guy https://github.com/blockstack/designs/issues/213)
- [x] Github - [github.com/blockstack](https://github.com/blockstack)
- [x] Wikipedia - [wikipedia.org/wiki/blockstack](https://en.wikipedia.org/wiki/Blockstack)
- [x] Medium - [blog.blockstack.org](https://blog.blockstack.org/)
- [x] https://github.com/blockstack/designs/issues/114: Forum - [forum.blockstack.org](https://forum.blockstack.org/)
- [x] Blockstack.id - [onename.com/blockstack](https://onename.com/blockstack)
- [x] Meetup.com
  - [x] Graphics - https://github.com/blockstack/designs/issues/145: (graphics complete)
  - [x] Uploaded to all meetup groups - https://github.com/blockstack/designs/issues/153
- [x] Onename.com - [onename.com](https://onename.com/)
- [x] Blockstack Block Explorer - [explorer.blockstack.org](https://explorer.blockstack.org/)

Not to be created
- [x] ~~Pinterest - (needs to be created)~~
- [x] ~~Vimeo - (needs to be created)~~

**Comment by guylepage3** [comment]
complete. Wikipedia logo update

**Comment by guylepage3** [comment]
complete by @larrysalibra #114: Forum - forum.blockstack.org

**Comment by guylepage3** [comment]
@pstan26 can you check off the above checkbox once completed uploading the meetup banner to all meetup groups? Thanks. https://github.com/blockstack/designs/issues/153

**Comment by pstan26** [comment]
Yes, will do. Just need need co-organizer status first to apply banner. Mentioned @shea256 in this task for help there: https://github.com/blockstack/designs/issues/153

**Comment by guylepage3** [comment]
Reassigning this task to @pstan26. If you could take this off my plate that would be a huge help. Logo's are here:

![blockstack-squared-512x512](https://cloud.githubusercontent.com/assets/1711854/23480750/0ec943f2-fe97-11e6-9a4a-a9b862efa6a0.png)

**Comment by pstan26** [comment]
A bit confused as to what is remaining in the task, as it looks like most of these have had the new logo applied and I only see that one logo in the comment above which see. Am I supposed to apply it to things like Blockstack Explorer? lmk

**Comment by guylepage3** [comment]
@pstan26 updated.

**Comment by guylepage3** [comment]
@pstan26 can you ask @shea256 @muneeb-ali if you can get access to https://www.linkedin.com/company-beta/10624288/ and update the logo with the one above? Also, I believe that we do not have the company name chosen for a custom URL.

**Comment by guylepage3** [comment]
hey @pstan26 just a reminder for updating our LinkedIn logo.

**Comment by guylepage3** [comment]
hey @pstan26 any luck with getting login credentials for updating the LinkedIn logo?

cc: @muneeb-ali @shea256

**Comment by pstan26** [comment]
Admin request pending

**Comment by guylepage3** [comment]
hey @pstan26 any luck with gaining admin access on this issue? cc: @shea256 @muneeb-ali

**Comment by guylepage3** [comment]
Or shall we hand this one off to @ginaabrams?

**Comment by shea256** [comment]
@pstan26 Approved.

**Comment by pstan26** [comment]
For some reason it is still saying admin request pending.
[image: Inline image 1]

**Comment by guylepage3** [comment]
@pstan26 @ginaabrams, any luck with this?

**Comment by guylepage3** [comment]
Reminder...
@pstan26 @GinaAbrams, any luck with this issue?

**Comment by GinaAbrams** [comment]
@guylepage3 @pstan26 requested admin access on LinkedIn account, hopefully can update asap!

**Comment by guylepage3** [comment]
Awesome. Looking forward to closing out this issue.

@GinaAbrams you may need to direct message @shea256 or @muneeb-ali directly to let them know you've requested access.

**Comment by guylepage3** [comment]
Whoot! I see LinkedIn is updated. Closing this issue.
